// This prevents pollution of the global namespace
var SQL = (function () {
  var Module = window.Module;
var e;e||(e=eval("(function() { try { return Module || {} } catch(e) { return {} } })()"));var aa={},ba;for(ba in e)e.hasOwnProperty(ba)&&(aa[ba]=e[ba]);var da=!1,ea=!1,k=!1,fa=!1;
if(e.ENVIRONMENT)if("WEB"===e.ENVIRONMENT)da=!0;else if("WORKER"===e.ENVIRONMENT)ea=!0;else if("NODE"===e.ENVIRONMENT)k=!0;else if("SHELL"===e.ENVIRONMENT)fa=!0;else throw Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.");else da="object"===typeof window,ea="function"===typeof importScripts,k="object"===typeof process&&"function"===typeof require&&!da&&!ea,fa=!da&&!k&&!ea;
if(k){e.print||(e.print=console.log);e.printErr||(e.printErr=console.warn);var ga,ia;e.read=function(a,b){ga||(ga=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);var c=ga.readFileSync(a);return b?c:c.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};e.load=function(a){ja(read(a))};e.thisProgram||(e.thisProgram=1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");e.arguments=process.argv.slice(2);"undefined"!==
typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;});e.inspect=function(){return"[Emscripten Module object]"}}else if(fa)e.print||(e.print=print),"undefined"!=typeof printErr&&(e.printErr=printErr),e.read="undefined"!=typeof read?read:function(){throw"no read() available";},e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?
e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)}),eval("if (typeof gc === 'function' && gc.toString().indexOf('[native code]') > 0) var gc = undefined");else if(da||ea)e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ea&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},"undefined"!=typeof arguments&&(e.arguments=arguments),"undefined"!==typeof console?(e.print||(e.print=function(a){console.log(a)}),e.printErr||(e.printErr=function(a){console.warn(a)})):e.print||(e.print=function(){}),ea&&(e.load=importScripts),"undefined"===typeof e.setWindowTitle&&(e.setWindowTitle=
function(a){document.title=a});else throw"Unknown runtime environment. Where are we?";function ja(a){eval.call(null,a)}!e.load&&e.read&&(e.load=function(a){ja(e.read(a))});e.print||(e.print=function(){});e.printErr||(e.printErr=e.print);e.arguments||(e.arguments=[]);e.thisProgram||(e.thisProgram="./this.program");e.quit||(e.quit=function(a,b){throw b;});e.print=e.print;e.W=e.printErr;e.preRun=[];e.postRun=[];for(ba in aa)aa.hasOwnProperty(ba)&&(e[ba]=aa[ba]);
var aa=void 0,n={qb:function(a){return tempRet0=a},hb:function(){return tempRet0},X:function(){return l},Q:function(a){l=a},Ga:function(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:return"*"===a[a.length-1]?n.ea:"i"===a[0]?(a=parseInt(a.substr(1)),assert(0===a%8),a/8):0}},eb:function(a){return Math.max(n.Ga(a),n.ea)},vd:16,Rd:function(a,b){"double"===b||"i64"===b?a&7&&(assert(4===(a&7)),a+=
4):assert(0===(a&3));return a},Gd:function(a,b,c){return c||"i64"!=a&&"double"!=a?a?Math.min(b||(a?n.eb(a):0),n.ea):Math.min(b,8):8},ha:function(a,b,c){return c&&c.length?e["dynCall_"+a].apply(null,[b].concat(c)):e["dynCall_"+a].call(null,b)},i:[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,
null,null,null,null,null,null,null,null,null,null,null,null,null],ua:function(a){for(var b=0;b<n.i.length;b++)if(!n.i[b])return n.i[b]=a,2*(1+b);throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";},mb:function(a){n.i[(a-2)/2]=null},K:function(a){n.K.oa||(n.K.oa={});n.K.oa[a]||(n.K.oa[a]=1,e.W(a))},ia:{},Jd:function(a,b){assert(b);n.ia[b]||(n.ia[b]={});var c=n.ia[b];c[a]||(c[a]=1===b.length?function(){return n.ha(b,a)}:2===b.length?function(c){return n.ha(b,
a,[c])}:function(){return n.ha(b,a,Array.prototype.slice.call(arguments))});return c[a]},Hd:function(){throw"You must build with -s RETAIN_COMPILER_SETTINGS=1 for Runtime.getCompilerSetting or emscripten_get_compiler_setting to work";},v:function(a){var b=l;l=l+a|0;l=l+15&-16;return b},pa:function(a){var b=p;p=p+a|0;p=p+15&-16;return b},Ba:function(a){var b=r[la>>2];a=(b+a+15|0)&-16;r[la>>2]=a;if(a=a>=ma)na(),a=!0;return a?(r[la>>2]=b,0):b},va:function(a,b){return Math.ceil(a/(b?b:16))*(b?b:16)},
Qd:function(a,b,c){return c?+(a>>>0)+4294967296*+(b>>>0):+(a>>>0)+4294967296*+(b|0)},da:1024,ea:4,wd:0};e.Runtime=n;n.addFunction=n.ua;n.removeFunction=n.mb;var oa=0;function assert(a,b){a||u("Assertion failed: "+b)}function pa(a){var b=e["_"+a];if(!b)try{b=eval("_"+a)}catch(c){}assert(b,"Cannot call unknown function "+a+" (perhaps LLVM optimizations or closure removed it?)");return b}var qa,ra;
(function(){function a(a){a=a.toString().match(f).slice(1);return{arguments:a[0],body:a[1],returnValue:a[2]}}function b(){if(!g){g={};for(var b in c)c.hasOwnProperty(b)&&(g[b]=a(c[b]))}}var c={stackSave:function(){n.X()},stackRestore:function(){n.Q()},arrayToC:function(a){var b=n.v(a.length);sa(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1,b=n.v(c);ta(a,b,c)}return b}},d={string:c.stringToC,array:c.arrayToC};ra=function(a,b,c,f,g){a=pa(a);var x=
[],C=0;if(f)for(var A=0;A<f.length;A++){var E=d[c[A]];E?(0===C&&(C=n.X()),x[A]=E(f[A])):x[A]=f[A]}c=a.apply(null,x);"string"===b&&(c=w(c));if(0!==C){if(g&&g.async){EmterpreterAsync.yd.push(function(){n.Q(C)});return}n.Q(C)}return c};var f=/^function\s*[a-zA-Z$_0-9]*\s*\(([^)]*)\)\s*{\s*([^*]*?)[\s;]*(?:return\s*(.*?)[;\s]*)?}$/,g=null;qa=function(c,d,f){f=f||[];var q=pa(c);c=f.every(function(a){return"number"===a});var v="string"!==d;if(v&&c)return q;var x=f.map(function(a,b){return"$"+b});d="(function("+
x.join(",")+") {";var C=f.length;if(!c){b();d+="var stack = "+g.stackSave.body+";";for(var A=0;A<C;A++){var E=x[A],ca=f[A];"number"!==ca&&(ca=g[ca+"ToC"],d+="var "+ca.arguments+" = "+E+";",d+=ca.body+";",d+=E+"=("+ca.returnValue+");")}}f=a(function(){return q}).returnValue;d+="var ret = "+f+"("+x.join(",")+");";v||(f=a(function(){return w}).returnValue,d+="ret = "+f+"(ret);");c||(b(),d+=g.stackRestore.body.replace("()","(stack)")+";");return eval(d+"return ret})")}})();e.ccall=ra;e.cwrap=qa;
function ua(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":y[a>>0]=b;break;case "i8":y[a>>0]=b;break;case "i16":va[a>>1]=b;break;case "i32":r[a>>2]=b;break;case "i64":tempI64=[b>>>0,(tempDouble=b,1<=+wa(tempDouble)?0<tempDouble?(xa(+ya(tempDouble/4294967296),4294967295)|0)>>>0:~~+za((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];r[a>>2]=tempI64[0];r[a+4>>2]=tempI64[1];break;case "float":Aa[a>>2]=b;break;case "double":Ba[a>>3]=b;break;default:u("invalid type for setValue: "+
c)}}e.setValue=ua;function Ca(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return y[a>>0];case "i8":return y[a>>0];case "i16":return va[a>>1];case "i32":return r[a>>2];case "i64":return r[a>>2];case "float":return Aa[a>>2];case "double":return Ba[a>>3];default:u("invalid type for setValue: "+b)}return null}e.getValue=Ca;e.ALLOC_NORMAL=0;e.ALLOC_STACK=1;e.ALLOC_STATIC=2;e.ALLOC_DYNAMIC=3;e.ALLOC_NONE=4;
function z(a,b,c,d){var f,g;"number"===typeof a?(f=!0,g=a):(f=!1,g=a.length);var h="string"===typeof b?b:null,m;4==c?m=d:m=["function"===typeof Da?Da:n.pa,n.v,n.pa,n.Ba][void 0===c?2:c](Math.max(g,h?1:b.length));if(f){d=m;assert(0==(m&3));for(a=m+(g&-4);d<a;d+=4)r[d>>2]=0;for(a=m+g;d<a;)y[d++>>0]=0;return m}if("i8"===h)return a.subarray||a.slice?B.set(a,m):B.set(new Uint8Array(a),m),m;d=0;for(var t,q;d<g;)f=a[d],"function"===typeof f&&(f=n.Kd(f)),c=h||b[d],0===c?d++:("i64"==c&&(c="i32"),ua(m+d,f,
c),q!==c&&(t=n.Ga(c),q=c),d+=t);return m}e.allocate=z;e.getMemory=function(a){return Ea?Fa?Da(a):n.Ba(a):n.pa(a)};function w(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=B[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,B.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return e.UTF8ToString(a)}e.Pointer_stringify=w;e.AsciiToString=function(a){for(var b="";;){var c=y[a++>>0];if(!c)return b;b+=String.fromCharCode(c)}};
e.stringToAscii=function(a,b){return Ga(a,b,!1)};var Ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ia(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&Ha)return Ha.decode(a.subarray(b,c));for(var d,f,g,h,m,t,c="";;){d=a[b++];if(!d)return c;d&128?(f=a[b++]&63,192==(d&224)?c+=String.fromCharCode((d&31)<<6|f):(g=a[b++]&63,224==(d&240)?d=(d&15)<<12|f<<6|g:(h=a[b++]&63,240==(d&248)?d=(d&7)<<18|f<<12|g<<6|h:(m=a[b++]&63,248==(d&252)?d=(d&3)<<24|f<<18|g<<12|h<<6|m:(t=a[b++]&63,d=(d&1)<<30|f<<24|g<<18|h<<12|m<<6|t))),65536>d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(55296|d>>
10,56320|d&1023)))):c+=String.fromCharCode(d)}}e.UTF8ArrayToString=Ia;e.UTF8ToString=function(a){return Ia(B,a)};
function Ja(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=128|
h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}e.stringToUTF8Array=Ja;function ta(a,b,c){return Ja(a,B,b,c)}e.stringToUTF8=ta;function Ka(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}e.lengthBytesUTF8=Ka;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function La(a){return a.replace(/__Z[\w\d_]+/g,function(a){var c;a:{var d=e.___cxa_demangle||e.__cxa_demangle;if(d)try{var f=a.substr(1),g=Ka(f)+1,h=Da(g);ta(f,h,g);var m=Da(4),t=d(h,0,0,m);if(0===Ca(m,"i32")&&t){c=w(t);break a}}catch(q){}finally{h&&Ma(h),m&&Ma(m),t&&Ma(t)}else n.K("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");c=a}return a===c?a:a+" ["+c+"]"})}
function Na(){var a;a:{a=Error();if(!a.stack){try{throw Error(0);}catch(b){a=b}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}e.extraStackTrace&&(a+="\n"+e.extraStackTrace());return La(a)}e.stackTrace=Na;var buffer,y,B,va,Oa,r,Pa,Aa,Ba;
function Qa(){e.HEAP8=y=new Int8Array(buffer);e.HEAP16=va=new Int16Array(buffer);e.HEAP32=r=new Int32Array(buffer);e.HEAPU8=B=new Uint8Array(buffer);e.HEAPU16=Oa=new Uint16Array(buffer);e.HEAPU32=Pa=new Uint32Array(buffer);e.HEAPF32=Aa=new Float32Array(buffer);e.HEAPF64=Ba=new Float64Array(buffer)}var Sa,p,Ea,Ta,l,Ua,Va,la;Sa=p=Ta=l=Ua=Va=la=0;Ea=!1;
function na(){u("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+ma+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Wa=e.TOTAL_STACK||5242880,ma=e.TOTAL_MEMORY||16777216;ma<Wa&&e.W("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+ma+"! (TOTAL_STACK="+Wa+")");
e.buffer?buffer=e.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:ma/65536,maximum:ma/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(ma);Qa();r[0]=1668509029;va[1]=25459;if(115!==B[2]||99!==B[3])throw"Runtime error: expected the system to be little-endian!";e.HEAP=void 0;e.buffer=buffer;e.HEAP8=y;e.HEAP16=va;e.HEAP32=r;e.HEAPU8=B;e.HEAPU16=Oa;e.HEAPU32=Pa;e.HEAPF32=Aa;e.HEAPF64=Ba;
function Xa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Fd;"number"===typeof c?void 0===b.ga?e.dynCall_v(c):e.dynCall_vi(c,b.ga):c(void 0===b.ga?null:b.ga)}}}var Ya=[],Za=[],$a=[],ab=[],bb=[],Fa=!1;function cb(a){Ya.unshift(a)}e.addOnPreRun=cb;e.addOnInit=function(a){Za.unshift(a)};e.addOnPreMain=function(a){$a.unshift(a)};e.addOnExit=function(a){ab.unshift(a)};function db(a){bb.unshift(a)}e.addOnPostRun=db;
function D(a,b,c){c=Array(0<c?c:Ka(a)+1);a=Ja(a,c,0,c.length);b&&(c.length=a);return c}e.intArrayFromString=D;e.intArrayToString=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];255<d&&(d&=255);b.push(String.fromCharCode(d))}return b.join("")};e.writeStringToMemory=function(a,b,c){n.K("writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!");var d,f;c&&(f=b+Ka(a),d=y[f]);ta(a,b,Infinity);c&&(y[f]=d)};function sa(a,b){y.set(a,b)}e.writeArrayToMemory=sa;
function Ga(a,b,c){for(var d=0;d<a.length;++d)y[b++>>0]=a.charCodeAt(d);c||(y[b>>0]=0)}e.writeAsciiToMemory=Ga;Math.imul&&-5===Math.imul(4294967295,5)||(Math.imul=function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16)*d+c*(b>>>16)<<16)|0});Math.Ld=Math.imul;if(!Math.fround){var eb=new Float32Array(1);Math.fround=function(a){eb[0]=a;return eb[0]}}Math.Ed=Math.fround;Math.clz32||(Math.clz32=function(a){a=a>>>0;for(var b=0;32>b;b++)if(a&1<<31-b)return b;return 32});Math.Bd=Math.clz32;
Math.trunc||(Math.trunc=function(a){return 0>a?Math.ceil(a):Math.floor(a)});Math.trunc=Math.trunc;var wa=Math.abs,za=Math.ceil,ya=Math.floor,fb=Math.pow,xa=Math.min,gb=0,hb=null,ib=null;function jb(){gb++;e.monitorRunDependencies&&e.monitorRunDependencies(gb)}e.addRunDependency=jb;function kb(){gb--;e.monitorRunDependencies&&e.monitorRunDependencies(gb);if(0==gb&&(null!==hb&&(clearInterval(hb),hb=null),ib)){var a=ib;ib=null;a()}}e.removeRunDependency=kb;e.preloadedImages={};e.preloadedAudios={};
var G=null;
(function(a){function b(b){var c=a.usingWasm?65536:16777216;0<b%c&&(b+=c-b%c);var c=a.buffer,d=c.byteLength;if(a.usingWasm)try{return-1!==a.wasmMemory.grow((b-d)/65536)?a.buffer=a.wasmMemory.buffer:null}catch(f){return null}else return A.__growWasmMemory((b-d)/65536),a.buffer!==c?a.buffer:null}function c(a,b){var c=C;if(0>a.indexOf("."))c=(c||{})[a];else var d=a.split("."),c=(c||{})[d[0]],c=(c||{})[d[1]];b&&(c=(c||{})[b]);void 0===c&&u("bad lookupImport to ("+a+")."+b);return c}function d(b){var c=a.buffer;
b.byteLength<c.byteLength&&a.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");var c=new Int8Array(c),d=new Int8Array(b);G||c.set(d.subarray(a.STATIC_BASE,a.STATIC_BASE+a.STATIC_BUMP),a.STATIC_BASE);d.set(c);e.buffer=buffer=b;Qa()}function f(){var b;if(a.wasmBinary)b=a.wasmBinary,b=new Uint8Array(b);else if(a.readBinary)b=a.readBinary(v);else throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";
return b}function g(){return a.wasmBinary||"function"!==typeof fetch?new Promise(function(a){a(f())}):fetch(v,{Cd:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+v+"'";return a.arrayBuffer()})}function h(b,c,d){if("function"!==typeof a.asm||a.asm===ha)a.asmPreload?a.asm=a.asmPreload:eval(a.read(x));return"function"!==typeof a.asm?(a.printErr("asm evalling did not set the module properly"),!1):a.asm(b,c,d)}function m(b,c){function f(b){A=b.exports;A.memory&&d(A.memory);
a.asm=A;a.usingWasm=!0;kb()}if("object"!==typeof WebAssembly)return a.printErr("no native wasm support detected"),!1;if(!(a.wasmMemory instanceof WebAssembly.Memory))return a.printErr("no native wasm Memory in use"),!1;c.memory=a.wasmMemory;C.global={NaN:NaN,Infinity:Infinity};C["global.Math"]=b.Math;C.env=c;jb();if(a.instantiateWasm)try{return a.instantiateWasm(C,f)}catch(h){return a.printErr("Module.instantiateWasm callback failed with error: "+h),!1}g().then(function(a){return WebAssembly.instantiate(a,
C)}).then(function(a){f(a.instance)}).catch(function(b){a.printErr("failed to asynchronously prepare wasm: "+b);a.quit(1,b)});return{}}var t=a.wasmJSMethod||"native-wasm";a.wasmJSMethod=t;var q=a.wasmTextFile||"sql-optimized-wasm-raw.wast",v=a.wasmBinaryFile||"sql-optimized-wasm-raw.wasm",x=a.asmjsCodeFile||"sql-optimized-wasm-raw.temp.asm.js";"function"===typeof a.locateFile&&(q=a.locateFile(q),v=a.locateFile(v),x=a.locateFile(x));var C={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%
b},"f64-to-int":function(a){return a|0},"i32s-div":function(a,b){return(a|0)/(b|0)|0},"i32u-div":function(a,b){return(a>>>0)/(b>>>0)>>>0},"i32s-rem":function(a,b){return(a|0)%(b|0)|0},"i32u-rem":function(a,b){return(a>>>0)%(b>>>0)>>>0},"debugger":function(){debugger}},parent:a},A=null;a.asmPreload=a.asm;var E=a.reallocBuffer;a.reallocBuffer=function(a){return"asmjs"===ca?E(a):b(a)};var ca="";a.asm=function(b,g,v){if(!g.table){var E=a.wasmTableSize;void 0===E&&(E=1024);var ha=a.wasmMaxTableSize;g.table=
"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==ha?new WebAssembly.Table({initial:E,maximum:ha,element:"anyfunc"}):new WebAssembly.Table({initial:E,element:"anyfunc"}):Array(E);a.wasmTable=g.table}g.memoryBase||(g.memoryBase=a.STATIC_BASE);g.tableBase||(g.tableBase=0);for(var F,E=t.split(","),ha=0;ha<E.length;ha++)if(ca=F=E[ha],"native-wasm"===F){if(F=m(b,g))break}else if("asmjs"===F){if(F=h(b,g,v))break}else if("interpret-asm2wasm"===F||"interpret-s-expr"===F||"interpret-binary"===
F){var W=b,I=g,vb=v;if("function"!==typeof WasmJS)a.printErr("WasmJS not detected - polyfill not bundled?"),F=!1;else{var H=WasmJS({});H.outside=a;H.info=C;H.lookupImport=c;assert(vb===a.buffer);C.global=W;C.env=I;assert(vb===a.buffer);I.memory=vb;assert(I.memory instanceof ArrayBuffer);H.providedTotalMemory=a.buffer.byteLength;W=void 0;W="interpret-binary"===F?f():a.read("interpret-asm2wasm"==F?x:q);I=void 0;if("interpret-asm2wasm"==F)I=H._malloc(W.length+1),H.writeAsciiToMemory(W,I),H._load_asm2wasm(I);
else if("interpret-s-expr"===F)I=H._malloc(W.length+1),H.writeAsciiToMemory(W,I),H._load_s_expr2wasm(I);else if("interpret-binary"===F)I=H._malloc(W.length),H.HEAPU8.set(W,I),H._load_binary2wasm(I,W.length);else throw"what? "+F;H._free(I);H._instantiate(I);a.newBuffer&&(d(a.newBuffer),a.newBuffer=null);F=A=H.asmExports}if(F)break}else throw"bad method: "+F;if(!F)throw"no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods";
return F};var ha=a.asm})(e);Sa=n.da;p=Sa+25664;Za.push();G=0<=e.wasmJSMethod.indexOf("asmjs")||0<=e.wasmJSMethod.indexOf("interpret-asm2wasm")?"sql-optimized-wasm-raw.js.mem":null;e.STATIC_BASE=Sa;e.STATIC_BUMP=25664;var lb=p;p+=16;
var J={s:1,q:2,hd:3,dc:4,C:5,ta:6,xb:7,Bc:8,B:9,Lb:10,qa:11,sd:11,Pa:12,R:13,Xb:14,Nc:15,L:16,ra:17,td:18,ba:19,S:20,M:21,h:22,wc:23,Oa:24,Sc:25,pd:26,Yb:27,Jc:28,T:29,dd:30,pc:31,Yc:32,Ub:33,Qa:34,Fc:42,ac:43,Mb:44,gc:45,hc:46,ic:47,oc:48,qd:49,zc:50,fc:51,Rb:35,Cc:37,Db:52,Gb:53,ud:54,xc:55,Hb:56,Ib:57,Sb:35,Jb:59,Lc:60,Ac:61,md:62,Kc:63,Gc:64,Hc:65,cd:66,Dc:67,Ab:68,jd:69,Nb:70,Zc:71,rc:72,Vb:73,Fb:74,Tc:76,Eb:77,bd:78,jc:79,kc:80,nc:81,mc:82,lc:83,Mc:38,sa:39,sc:36,aa:40,Uc:95,Xc:96,Qb:104,yc:105,
Bb:97,ad:91,Qc:88,Ic:92,ed:108,Pb:111,yb:98,Ob:103,vc:101,tc:100,nd:110,Zb:112,$b:113,cc:115,Cb:114,Tb:89,qc:90,$c:93,gd:94,zb:99,uc:102,ec:106,Oc:107,od:109,rd:87,Wb:122,kd:116,Rc:95,Ec:123,bc:84,Vc:75,Kb:125,Pc:131,Wc:130,ld:86},mb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function nb(a){e.___errno_location&&(r[e.___errno_location()>>2]=a);return a}
function ob(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c--;c)a.unshift("..");return a}function pb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ob(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function qb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function rb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function sb(){var a=Array.prototype.slice.call(arguments,0);return pb(a.join("/"))}function K(a,b){return pb(a+"/"+b)}
function tb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ob(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var ub=[];function wb(a,b){ub[a]={input:[],output:[],J:b};xb(a,yb)}
var yb={open:function(a){var b=ub[a.c.rdev];if(!b)throw new L(J.ba);a.tty=b;a.seekable=!1},close:function(a){a.tty.J.flush(a.tty)},flush:function(a){a.tty.J.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.J.Ha)throw new L(J.ta);for(var f=0,g=0;g<d;g++){var h;try{h=a.tty.J.Ha(a.tty)}catch(m){throw new L(J.C);}if(void 0===h&&0===f)throw new L(J.qa);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.c.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.J.ma)throw new L(J.ta);
for(var f=0;f<d;f++)try{a.tty.J.ma(a.tty,b[c+f])}catch(g){throw new L(J.C);}d&&(a.c.timestamp=Date.now());return f}},zb={Ha:function(a){if(!a.input.length){var b=null;if(k){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(m){if(-1!=m.toString().indexOf("EOF"))d=0;else throw m;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==
typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=D(b,!0)}return a.input.shift()},ma:function(a,b){null===b||10===b?(e.print(Ia(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(e.print(Ia(a.output,0)),a.output=[])}},Ab={ma:function(a,b){null===b||10===b?(e.printErr(Ia(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(e.printErr(Ia(a.output,0)),a.output=[])}},M={p:null,m:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(J.s);M.p||(M.p={dir:{c:{o:M.d.o,k:M.d.k,lookup:M.d.lookup,O:M.d.O,rename:M.d.rename,unlink:M.d.unlink,rmdir:M.d.rmdir,readdir:M.d.readdir,symlink:M.d.symlink},stream:{u:M.e.u}},file:{c:{o:M.d.o,k:M.d.k},stream:{u:M.e.u,read:M.e.read,write:M.e.write,wa:M.e.wa,Ka:M.e.Ka,Ma:M.e.Ma}},link:{c:{o:M.d.o,
k:M.d.k,readlink:M.d.readlink},stream:{}},Aa:{c:{o:M.d.o,k:M.d.k},stream:Bb}});c=Cb(a,b,c,d);N(c.mode)?(c.d=M.p.dir.c,c.e=M.p.dir.stream,c.b={}):32768===(c.mode&61440)?(c.d=M.p.file.c,c.e=M.p.file.stream,c.f=0,c.b=null):40960===(c.mode&61440)?(c.d=M.p.link.c,c.e=M.p.link.stream):8192===(c.mode&61440)&&(c.d=M.p.Aa.c,c.e=M.p.Aa.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},cb:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.f;++c)b.push(a.b[c]);return b}return a.b},Id:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.f):new Uint8Array(a.b):new Uint8Array},Ca:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=M.cb(a),a.f=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.f&&a.b.set(c.subarray(0,a.f),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},nb:function(a,b){if(a.f!=b)if(0==b)a.b=null,a.f=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.f)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.f=b}},d:{o:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.f:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.D=4096;b.blocks=Math.ceil(b.size/b.D);return b},
k:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.nb(a,b.size)},lookup:function(){throw Db[J.q];},O:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(N(a.mode)){var d;try{d=Eb(b,c)}catch(f){}if(d)for(var g in d.b)throw new L(J.sa);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=Eb(a,b),d;for(d in c.b)throw new L(J.sa);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(J.h);return a.link}},e:{read:function(a,b,c,d,f){var g=a.c.b;if(f>=a.c.f)return 0;a=Math.min(a.c.f-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.c;a.timestamp=Date.now();if(b.subarray&&(!a.b||
a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.f=d;if(0===a.f&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.f=d;if(f+d<=a.f)return a.b.set(b.subarray(c,c+d),f),d}M.Ca(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.f=Math.max(a.f,f+d);return d},u:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.c.mode&61440)&&(b+=a.c.f);if(0>b)throw new L(J.h);return b},wa:function(a,b,c){M.Ca(a.c,b+c);a.c.f=Math.max(a.c.f,b+c)},Ka:function(a,
b,c,d,f,g,h){if(32768!==(a.c.mode&61440))throw new L(J.ba);c=a.c.b;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.c.f)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=Da(d);if(!d)throw new L(J.Pa);b.set(c,d)}else a=!1,d=c.byteOffset;return{Sd:d,xd:a}},Ma:function(a,b,c,d,f){if(32768!==(a.c.mode&61440))throw new L(J.ba);if(f&2)return 0;M.e.write(a,b,0,d,c,!1);return 0}}},O={V:!1,rb:function(){O.V=!!process.platform.match(/^win/)},m:function(a){assert(k);return O.createNode(null,
"/",O.Fa(a.la.root),0)},createNode:function(a,b,c){if(!N(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(J.h);a=Cb(a,b,c);a.d=O.d;a.e=O.e;return a},Fa:function(a){var b;try{b=fs.lstatSync(a),O.V&&(b.mode=b.mode|(b.mode&146)>>1)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}return b.mode},n:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.m.la.root);b.reverse();return sb.apply(null,b)},Da:{0:"r",1:"r+",2:"r+",64:"r",65:"r+",66:"r+",129:"rx+",193:"rx+",514:"w+",577:"w",
578:"w+",705:"wx",706:"wx+",1024:"a",1025:"a",1026:"a+",1089:"a",1090:"a+",1153:"ax",1154:"ax+",1217:"ax",1218:"ax+",4096:"rs",4098:"rs+"},bb:function(a){a&=-2099201;a&=-32769;a&=-524289;if(a in O.Da)return O.Da[a];throw new L(J.h);},d:{o:function(a){a=O.n(a);var b;try{b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}O.V&&!b.D&&(b.D=4096);O.V&&!b.blocks&&(b.blocks=(b.size+b.D-1)/b.D|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,
atime:b.atime,mtime:b.mtime,ctime:b.ctime,D:b.D,blocks:b.blocks}},k:function(a,b){var c=O.n(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},lookup:function(a,b){var c=K(O.n(a),b),c=O.Fa(c);return O.createNode(a,b,c)},O:function(a,b,c,d){a=O.createNode(a,b,c,d);b=O.n(a);try{N(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new L(J[f.code]);
}return a},rename:function(a,b,c){a=O.n(a);b=K(O.n(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},unlink:function(a,b){var c=K(O.n(a),b);try{fs.unlinkSync(c)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},rmdir:function(a,b){var c=K(O.n(a),b);try{fs.rmdirSync(c)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},readdir:function(a){a=O.n(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(J[b.code]);}},symlink:function(a,b,c){a=K(O.n(a),
b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},readlink:function(a){var b=O.n(a);try{return b=fs.readlinkSync(b),b=Fb.relative(Fb.resolve(a.m.la.root),b)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}}},e:{open:function(a){var b=O.n(a.c);try{32768===(a.c.mode&61440)&&(a.P=fs.openSync(b,O.bb(a.flags)))}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}},close:function(a){try{32768===(a.c.mode&61440)&&a.P&&fs.closeSync(a.P)}catch(b){if(!b.code)throw b;throw new L(J[b.code]);
}},read:function(a,b,c,d,f){if(0===d)return 0;var g=new Buffer(d),h;try{h=fs.readSync(a.P,g,0,d,f)}catch(m){throw new L(J[m.code]);}if(0<h)for(a=0;a<h;a++)b[c+a]=g[a];return h},write:function(a,b,c,d,f){b=new Buffer(b.subarray(c,c+d));var g;try{g=fs.writeSync(a.P,b,0,d,f)}catch(h){throw new L(J[h.code]);}return g},u:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.c.mode&61440))try{b+=fs.fstatSync(a.P).size}catch(d){throw new L(J[d.code]);}if(0>b)throw new L(J.h);return b}}};p+=16;
p+=16;p+=16;var Gb=null,Hb=[null],P=[],Ib=1,Jb=null,Kb=!0,Q={},L=null,Db={};
function R(a,b){a=tb("/",a);b=b||{};if(!a)return{path:"",c:null};var c={Ea:!0,na:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.na)throw new L(J.aa);var c=ob(a.split("/").filter(function(a){return!!a}),!1),f=Gb;d="/";for(var g=0;g<c.length;g++){var h=g===c.length-1;if(h&&b.parent)break;f=Eb(f,c[g]);d=K(d,c[g]);f.H&&(!h||h&&b.Ea)&&(f=f.H.root);if(!h||b.F)for(h=0;40960===(f.mode&61440);)if(f=Lb(d),d=tb(qb(d),f),f=R(d,{na:b.na}).c,40<h++)throw new L(J.aa);}return{path:d,c:f}}
function S(a){for(var b;;){if(a===a.parent)return a=a.m.La,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Mb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Jb.length}function Nb(a){var b=Mb(a.parent.id,a.name);a.I=Jb[b];Jb[b]=a}function Ob(a){var b=Mb(a.parent.id,a.name);if(Jb[b]===a)Jb[b]=a.I;else for(b=Jb[b];b;){if(b.I===a){b.I=a.I;break}b=b.I}}
function Eb(a,b){var c;if(c=(c=Pb(a,"x"))?c:a.d.lookup?0:J.R)throw new L(c,a);for(c=Jb[Mb(a.id,b)];c;c=c.I){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.d.lookup(a,b)}
function Cb(a,b,c,d){Qb||(Qb=function(a,b,c,d){a||(a=this);this.parent=a;this.m=a.m;this.H=null;this.id=Ib++;this.name=b;this.mode=c;this.d={};this.e={};this.rdev=d},Qb.prototype={},Object.defineProperties(Qb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},jb:{get:function(){return N(this.mode)}},ib:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Qb(a,b,c,d);Nb(a);return a}function N(a){return 16384===(a&61440)}var Rb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Sb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Pb(a,b){if(Kb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return J.R}else return J.R;return 0}
function Tb(a,b){try{return Eb(a,b),J.ra}catch(c){}return Pb(a,"wx")}function Ub(a,b,c){var d;try{d=Eb(a,b)}catch(f){return f.g}if(a=Pb(a,"wx"))return a;if(c){if(!N(d.mode))return J.S;if(d===d.parent||"/"===S(d))return J.L}else if(N(d.mode))return J.M;return 0}function Vb(a){var b;b=4096;for(a=a||0;a<=b;a++)if(!P[a])return a;throw new L(J.Oa);}
function Wb(a,b){Xb||(Xb=function(){},Xb.prototype={},Object.defineProperties(Xb.prototype,{object:{get:function(){return this.c},set:function(a){this.c=a}},Od:{get:function(){return 1!==(this.flags&2097155)}},Pd:{get:function(){return 0!==(this.flags&2097155)}},Nd:{get:function(){return this.flags&1024}}}));var c=new Xb,d;for(d in a)c[d]=a[d];a=c;c=Vb(b);a.fd=c;return P[c]=a}var Bb={open:function(a){a.e=Hb[a.c.rdev].e;a.e.open&&a.e.open(a)},u:function(){throw new L(J.T);}};
function xb(a,b){Hb[a]={e:b}}function Yb(a,b){var c="/"===b,d=!b,f;if(c&&Gb)throw new L(J.L);if(!c&&!d){f=R(b,{Ea:!1});b=f.path;f=f.c;if(f.H)throw new L(J.L);if(!N(f.mode))throw new L(J.S);}var d={type:a,la:{},La:b,kb:[]},g=a.m(d);g.m=d;d.root=g;c?Gb=g:f&&(f.H=d,f.m&&f.m.kb.push(d))}function Zb(a,b,c){var d=R(a,{parent:!0}).c;a=rb(a);if(!a||"."===a||".."===a)throw new L(J.h);var f=Tb(d,a);if(f)throw new L(f);if(!d.d.O)throw new L(J.s);return d.d.O(d,a,b,c)}
function $b(a,b){b=(void 0!==b?b:438)&4095;b|=32768;return Zb(a,b,0)}function T(a,b){b=(void 0!==b?b:511)&1023;b|=16384;return Zb(a,b,0)}function ac(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Zb(a,b|8192,c)}function bc(a,b){if(!tb(a))throw new L(J.q);var c=R(b,{parent:!0}).c;if(!c)throw new L(J.q);var d=rb(b),f=Tb(c,d);if(f)throw new L(f);if(!c.d.symlink)throw new L(J.s);return c.d.symlink(c,d,a)}
function cc(a){var b=R(a,{parent:!0}).c,c=rb(a),d=Eb(b,c),f=Ub(b,c,!1);if(f)throw new L(f);if(!b.d.unlink)throw new L(J.s);if(d.H)throw new L(J.L);try{Q.willDeletePath&&Q.willDeletePath(a)}catch(g){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.d.unlink(b,c);Ob(d);try{if(Q.onDeletePath)Q.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+h.message)}}
function Lb(a){a=R(a).c;if(!a)throw new L(J.q);if(!a.d.readlink)throw new L(J.h);return tb(S(a.parent),a.d.readlink(a))}function dc(a,b){var c=R(a,{F:!b}).c;if(!c)throw new L(J.q);if(!c.d.o)throw new L(J.s);return c.d.o(c)}function ec(a){return dc(a,!0)}function fc(a,b){var c;"string"===typeof a?c=R(a,{F:!0}).c:c=a;if(!c.d.k)throw new L(J.s);c.d.k(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function gc(a){var b;"string"===typeof a?b=R(a,{F:!0}).c:b=a;if(!b.d.k)throw new L(J.s);b.d.k(b,{timestamp:Date.now()})}function hc(a,b){if(0>b)throw new L(J.h);var c;"string"===typeof a?c=R(a,{F:!0}).c:c=a;if(!c.d.k)throw new L(J.s);if(N(c.mode))throw new L(J.M);if(32768!==(c.mode&61440))throw new L(J.h);var d=Pb(c,"w");if(d)throw new L(d);c.d.k(c,{size:b,timestamp:Date.now()})}
function ic(a,b,c,d){if(""===a)throw new L(J.q);if("string"===typeof b){var f=Rb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;var g;if("object"===typeof a)g=a;else{a=pb(a);try{g=R(a,{F:!(b&131072)}).c}catch(h){}}f=!1;if(b&64)if(g){if(b&128)throw new L(J.ra);}else g=Zb(a,c,0),f=!0;if(!g)throw new L(J.q);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!N(g.mode))throw new L(J.S);if(!f&&(c=g?40960===(g.mode&61440)?J.aa:N(g.mode)&&
("r"!==Sb(b)||b&512)?J.M:Pb(g,Sb(b)):J.q))throw new L(c);b&512&&hc(g,0);b&=-641;d=Wb({c:g,path:S(g),flags:b,seekable:!0,position:0,e:g.e,wb:[],error:!1},d);d.e.open&&d.e.open(d);!e.logReadFiles||b&1||(jc||(jc={}),a in jc||(jc[a]=1,e.printErr("read file: "+a)));try{Q.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Q.onOpenFile(a,g))}catch(m){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}
function kc(a){a.ja&&(a.ja=null);try{a.e.close&&a.e.close(a)}catch(b){throw b;}finally{P[a.fd]=null}}function lc(a,b,c){if(!a.seekable||!a.e.u)throw new L(J.T);a.position=a.e.u(a,b,c);a.wb=[]}function mc(a,b,c,d,f){if(0>d||0>f)throw new L(J.h);if(1===(a.flags&2097155))throw new L(J.B);if(N(a.c.mode))throw new L(J.M);if(!a.e.read)throw new L(J.h);var g=!0;if("undefined"===typeof f)f=a.position,g=!1;else if(!a.seekable)throw new L(J.T);b=a.e.read(a,b,c,d,f);g||(a.position+=b);return b}
function nc(a,b,c,d,f,g){if(0>d||0>f)throw new L(J.h);if(0===(a.flags&2097155))throw new L(J.B);if(N(a.c.mode))throw new L(J.M);if(!a.e.write)throw new L(J.h);a.flags&1024&&lc(a,0,2);var h=!0;if("undefined"===typeof f)f=a.position,h=!1;else if(!a.seekable)throw new L(J.T);b=a.e.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&Q.onWriteToFile)Q.onWriteToFile(a.path)}catch(m){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+m.message)}return b}
function oc(){L||(L=function(a,b){this.c=b;this.pb=function(a){this.g=a;for(var b in J)if(J[b]===a){this.code=b;break}};this.pb(a);this.message=mb[a]},L.prototype=Error(),L.prototype.constructor=L,[J.q].forEach(function(a){Db[a]=new L(a);Db[a].stack="<generic error, no stack>"}))}var pc;function qc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function rc(a,b,c,d){a=K("string"===typeof a?a:S(a),b);return $b(a,qc(c,d))}
function sc(a,b,c,d,f,g){a=b?K("string"===typeof a?a:S(a),b):a;d=qc(d,f);f=$b(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}fc(f,d|146);a=ic(f,"w");nc(a,c,0,c.length,0,g);kc(a);fc(f,d)}return f}
function tc(a,b,c,d){a=K("string"===typeof a?a:S(a),b);b=qc(!!c,!!d);tc.Ja||(tc.Ja=64);var f=tc.Ja++<<8|0;xb(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var q=0,v=0;v<f;v++){var x;try{x=c()}catch(C){throw new L(J.C);}if(void 0===x&&0===q)throw new L(J.qa);if(null===x||void 0===x)break;q++;b[d+v]=x}q&&(a.c.timestamp=Date.now());return q},write:function(a,b,c,f){for(var q=0;q<f;q++)try{d(b[c+q])}catch(v){throw new L(J.C);}f&&(a.c.timestamp=
Date.now());return q}});return ac(a,b,f)}
function uc(a){if(a.ib||a.jb||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.b=D(e.read(a.url),!0),a.f=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||nb(J.C);return b}var U={},Qb,Xb,jc;
function vc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.c&&pb(b)!==pb(S(f.c)))return-J.S;throw f;}r[c>>2]=d.dev;r[c+4>>2]=0;r[c+8>>2]=d.ino;r[c+12>>2]=d.mode;r[c+16>>2]=d.nlink;r[c+20>>2]=d.uid;r[c+24>>2]=d.gid;r[c+28>>2]=d.rdev;r[c+32>>2]=0;r[c+36>>2]=d.size;r[c+40>>2]=4096;r[c+44>>2]=d.blocks;r[c+48>>2]=d.atime.getTime()/1E3|0;r[c+52>>2]=0;r[c+56>>2]=d.mtime.getTime()/1E3|0;r[c+60>>2]=0;r[c+64>>2]=d.ctime.getTime()/1E3|0;r[c+68>>2]=0;r[c+72>>2]=d.ino;return 0}var V=0;
function X(){V+=4;return r[V-4>>2]}function Y(){return w(X())}function wc(){var a;a=X();a=P[a];if(!a)throw new L(J.B);return a}e._memset=xc;function yc(a){a=a/1E3;if((da||ea)&&self.performance&&self.performance.now)for(var b=self.performance.now();self.performance.now()-b<a;);else for(b=Date.now();Date.now()-b<a;);return 0}e._usleep=yc;e._memcpy=zc;e._llvm_bswap_i32=Ac;var Bc=p;p+=48;var Cc=z(D("GMT"),"i8",2);
function Dc(a,b){var c=new Date(1E3*r[a>>2]);r[b>>2]=c.getUTCSeconds();r[b+4>>2]=c.getUTCMinutes();r[b+8>>2]=c.getUTCHours();r[b+12>>2]=c.getUTCDate();r[b+16>>2]=c.getUTCMonth();r[b+20>>2]=c.getUTCFullYear()-1900;r[b+24>>2]=c.getUTCDay();r[b+36>>2]=0;r[b+32>>2]=0;r[b+28>>2]=(c.getTime()-Date.UTC(c.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;r[b+40>>2]=Cc;return b}var Ec=p;p+=16;
function Fc(a){var b,c;Fc.N?(c=r[Ec>>2],b=r[c>>2]):(Fc.N=!0,Gc.USER=Gc.LOGNAME="web_user",Gc.PATH="/",Gc.PWD="/",Gc.HOME="/home/web_user",Gc.LANG="C",Gc._=e.thisProgram,b=z(1024,"i8",2),c=z(256,"i8*",2),r[c>>2]=b,r[Ec>>2]=c);var d=[],f=0,g;for(g in a)if("string"===typeof a[g]){var h=g+"="+a[g];d.push(h);f+=h.length}if(1024<f)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(a=0;a<d.length;a++)h=d[a],Ga(h,b),r[c+4*a>>2]=b,b+=h.length+1;r[c+4*d.length>>2]=0}var Gc={};
function Hc(a){if(0===a)return 0;a=w(a);if(!Gc.hasOwnProperty(a))return 0;Hc.N&&Ma(Hc.N);Hc.N=z(D(Gc[a]),"i8",0);return Hc.N}e._sbrk=Ic;e._memmove=Jc;function Kc(a,b){V=b;return 0}function Lc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Mc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Nc=[31,29,31,30,31,30,31,31,30,31,30,31],Oc=[31,28,31,30,31,30,31,31,30,31,30,31];
function Pc(a,b){for(var c=new Date(a.getTime());0<b;){var d=c.getMonth(),f=(Lc(c.getFullYear())?Nc:Oc)[d];if(b>f-c.getDate())b-=f-c.getDate()+1,c.setDate(1),11>d?c.setMonth(d+1):(c.setMonth(0),c.setFullYear(c.getFullYear()+1));else{c.setDate(c.getDate()+b);break}}return c}oc();Jb=Array(4096);Yb(M,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");xb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});ac("/dev/null",259);wb(1280,zb);wb(1536,Ab);ac("/dev/tty",1280);ac("/dev/tty1",1536);var a;if("undefined"!==typeof crypto){var b=new Uint8Array(1);a=function(){crypto.getRandomValues(b);return b[0]}}else a=k?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};tc("/dev","random",a);tc("/dev","urandom",a);T("/dev/shm");T("/dev/shm/tmp")})();T("/proc");T("/proc/self");
T("/proc/self/fd");Yb({m:function(){var a=Cb("/proc/self","fd",16895,73);a.d={lookup:function(a,c){var d=P[+c];if(!d)throw new L(J.B);var f={parent:null,m:{La:"fake"},d:{readlink:function(){return d.path}}};return f.parent=f}};return a}},"/proc/self/fd");
Za.unshift(function(){if(!e.noFSInit&&!pc){assert(!pc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");pc=!0;oc();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?tc("/dev","stdin",e.stdin):bc("/dev/tty","/dev/stdin");e.stdout?tc("/dev","stdout",null,e.stdout):bc("/dev/tty","/dev/stdout");e.stderr?tc("/dev","stderr",null,e.stderr):bc("/dev/tty1","/dev/stderr");
var a=ic("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=ic("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=ic("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});$a.push(function(){Kb=!1});ab.push(function(){pc=!1;var a=e._fflush;a&&a(0);for(a=0;a<P.length;a++){var b=P[a];b&&kc(b)}});e.FS_createFolder=function(a,b,c,d){a=K("string"===typeof a?a:S(a),b);return T(a,qc(c,d))};
e.FS_createPath=function(a,b){a="string"===typeof a?a:S(a);for(var c=b.split("/").reverse();c.length;){var d=c.pop();if(d){var f=K(a,d);try{T(f)}catch(g){}a=f}}return f};e.FS_createDataFile=sc;
e.FS_createPreloadedFile=function(a,b,c,d,f,g,h,m,t,q){function v(c){function A(c){q&&q();m||sc(a,b,c,d,f,t);g&&g();kb()}var E=!1;e.preloadPlugins.forEach(function(a){!E&&a.canHandle(x)&&(a.handle(c,x,A,function(){h&&h();kb()}),E=!0)});E||A(c)}Browser.Md();var x=b?tb(K(a,b)):a;jb();"string"==typeof c?Browser.zd(c,function(a){v(a)},h):v(c)};
e.FS_createLazyFile=function(a,b,c,d,f){var g,h;function m(){this.ka=!1;this.U=[]}m.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Ia(a/this.chunkSize|0)[b]}};m.prototype.ob=function(a){this.Ia=a};m.prototype.za=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d,a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d,g=1048576;f||(g=b);var h=this;h.ob(function(a){var d=a*g,f=(a+1)*g-1,f=Math.min(f,b-1);if("undefined"===typeof h.U[a]){var A=h.U;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var m=new XMLHttpRequest;m.open("GET",c,!1);b!==g&&m.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(m.responseType="arraybuffer");
m.overrideMimeType&&m.overrideMimeType("text/plain; charset=x-user-defined");m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);d=void 0!==m.response?new Uint8Array(m.response||[]):D(m.responseText||"",!0);A[a]=d}if("undefined"===typeof h.U[a])throw Error("doXHR failed!");return h.U[a]});if(a||!b)g=b=1,g=b=this.Ia(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ta=b;this.Sa=
g;this.ka=!0};if("undefined"!==typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";g=new m;Object.defineProperties(g,{length:{get:function(){this.ka||this.za();return this.Ta}},chunkSize:{get:function(){this.ka||this.za();return this.Sa}}});h=void 0}else h=c,g=void 0;var t=rc(a,b,d,f);g?t.b=g:h&&(t.b=null,t.url=h);Object.defineProperties(t,{f:{get:function(){return this.b.length}}});var q={};Object.keys(t.e).forEach(function(a){var b=
t.e[a];q[a]=function(){if(!uc(t))throw new L(J.C);return b.apply(null,arguments)}});q.read=function(a,b,c,d,f){if(!uc(t))throw new L(J.C);a=a.c.b;if(f>=a.length)return 0;d=Math.min(a.length-f,d);assert(0<=d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};t.e=q;return t};e.FS_createLink=function(a,b,c){a=K("string"===typeof a?a:S(a),b);return bc(c,a)};e.FS_createDevice=tc;e.FS_unlink=cc;Za.unshift(function(){});ab.push(function(){});
if(k){var fs=require("fs"),Fb=require("path");O.rb()}Fc(Gc);la=z(1,"i32",2);Ta=l=n.va(p);Ua=Ta+Wa;Va=n.va(Ua);r[la>>2]=Va;Ea=!0;e.wasmTableSize=4352;e.wasmMaxTableSize=4352;e.Ua={Math:Math,Int8Array:Int8Array,Int16Array:Int16Array,Int32Array:Int32Array,Uint8Array:Uint8Array,Uint16Array:Uint16Array,Uint32Array:Uint32Array,Float32Array:Float32Array,Float64Array:Float64Array,NaN:NaN,Infinity:Infinity};
e.Va={abort:u,assert:assert,enlargeMemory:function(){na()},getTotalMemory:function(){return ma},abortOnCannotGrowMemory:na,invoke_iiii:function(a,b,c,d){try{return e.dynCall_iiii(a,b,c,d)}catch(f){if("number"!==typeof f&&"longjmp"!==f)throw f;e.setThrew(1,0)}},jsCall_iiii:function(a,b,c,d){return n.i[a](b,c,d)},invoke_viiiij:function(a,b,c,d,f,g,h){try{e.dynCall_viiiij(a,b,c,d,f,g,h)}catch(m){if("number"!==typeof m&&"longjmp"!==m)throw m;e.setThrew(1,0)}},jsCall_viiiij:function(a,b,c,d,f,g){n.i[a](b,
c,d,f,g)},invoke_viiii:function(a,b,c,d,f){try{e.dynCall_viiii(a,b,c,d,f)}catch(g){if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},jsCall_viiii:function(a,b,c,d,f){n.i[a](b,c,d,f)},invoke_i:function(a){try{return e.dynCall_i(a)}catch(b){if("number"!==typeof b&&"longjmp"!==b)throw b;e.setThrew(1,0)}},jsCall_i:function(a){return n.i[a]()},invoke_vi:function(a,b){try{e.dynCall_vi(a,b)}catch(c){if("number"!==typeof c&&"longjmp"!==c)throw c;e.setThrew(1,0)}},jsCall_vi:function(a,b){n.i[a](b)},
invoke_viji:function(a,b,c,d,f){try{e.dynCall_viji(a,b,c,d,f)}catch(g){if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},jsCall_viji:function(a,b,c,d){n.i[a](b,c,d)},invoke_vii:function(a,b,c){try{e.dynCall_vii(a,b,c)}catch(d){if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},jsCall_vii:function(a,b,c){n.i[a](b,c)},invoke_iiiiiii:function(a,b,c,d,f,g,h){try{return e.dynCall_iiiiiii(a,b,c,d,f,g,h)}catch(m){if("number"!==typeof m&&"longjmp"!==m)throw m;e.setThrew(1,0)}},
jsCall_iiiiiii:function(a,b,c,d,f,g,h){return n.i[a](b,c,d,f,g,h)},invoke_ii:function(a,b){try{return e.dynCall_ii(a,b)}catch(c){if("number"!==typeof c&&"longjmp"!==c)throw c;e.setThrew(1,0)}},jsCall_ii:function(a,b){return n.i[a](b)},invoke_iiiij:function(a,b,c,d,f,g){try{return e.dynCall_iiiij(a,b,c,d,f,g)}catch(h){if("number"!==typeof h&&"longjmp"!==h)throw h;e.setThrew(1,0)}},jsCall_iiiij:function(a,b,c,d,f){return n.i[a](b,c,d,f)},invoke_viii:function(a,b,c,d){try{e.dynCall_viii(a,b,c,d)}catch(f){if("number"!==
typeof f&&"longjmp"!==f)throw f;e.setThrew(1,0)}},jsCall_viii:function(a,b,c,d){n.i[a](b,c,d)},invoke_iiji:function(a,b,c,d,f){try{return e.dynCall_iiji(a,b,c,d,f)}catch(g){if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},jsCall_iiji:function(a,b,c,d){return n.i[a](b,c,d)},invoke_iiiii:function(a,b,c,d,f){try{return e.dynCall_iiiii(a,b,c,d,f)}catch(g){if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},jsCall_iiiii:function(a,b,c,d,f){return n.i[a](b,c,d,f)},invoke_iijii:function(a,
b,c,d,f,g){try{return e.dynCall_iijii(a,b,c,d,f,g)}catch(h){if("number"!==typeof h&&"longjmp"!==h)throw h;e.setThrew(1,0)}},jsCall_iijii:function(a,b,c,d,f){return n.i[a](b,c,d,f)},invoke_iii:function(a,b,c){try{return e.dynCall_iii(a,b,c)}catch(d){if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},jsCall_iii:function(a,b,c){return n.i[a](b,c)},invoke_iiiiii:function(a,b,c,d,f,g){try{return e.dynCall_iiiiii(a,b,c,d,f,g)}catch(h){if("number"!==typeof h&&"longjmp"!==h)throw h;e.setThrew(1,
0)}},jsCall_iiiiii:function(a,b,c,d,f,g){return n.i[a](b,c,d,f,g)},invoke_iij:function(a,b,c,d){try{return e.dynCall_iij(a,b,c,d)}catch(f){if("number"!==typeof f&&"longjmp"!==f)throw f;e.setThrew(1,0)}},jsCall_iij:function(a,b,c){return n.i[a](b,c)},___syscall221:function(a,b){V=b;try{var c=wc();switch(X()){case 0:var d=X();return 0>d?-J.h:ic(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=X(),c.flags|=d,0;case 12:case 12:return d=X(),va[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;
case 16:case 8:return-J.h;case 9:return nb(J.h),-1;default:return-J.h}}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.g}},___syscall85:function(a,b){V=b;try{var c=Y(),d=X(),f;var g=X();if(0>=g)f=-J.h;else{var h=Lb(c),m=Math.min(g,Ka(h)),t=y[d+m];ta(h,d,g+1);y[d+m]=t;f=m}return f}catch(q){return"undefined"!==typeof U&&q instanceof L||u(q),-q.g}},_utimes:function(a,b){var c;b?(c=1E3*r[b+8>>2],c+=r[b+12>>2]/1E3):c=Date.now();a=w(a);try{var d=c,f=R(a,{F:!0}).c;f.d.k(f,{timestamp:Math.max(d,
c)});return 0}catch(g){if(!(g instanceof L))throw g+" : "+Na();nb(g.g);return-1}},_llvm_pow_f64:fb,_abort:function(){e.abort()},___syscall40:function(a,b){V=b;try{var c=Y(),d=R(c,{parent:!0}).c,f=rb(c),g=Eb(d,f),h=Ub(d,f,!0);if(h)throw new L(h);if(!d.d.rmdir)throw new L(J.s);if(g.H)throw new L(J.L);try{Q.willDeletePath&&Q.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}d.d.rmdir(d,f);Ob(g);try{if(Q.onDeletePath)Q.onDeletePath(c)}catch(t){console.log("FS.trackingDelegate['onDeletePath']('"+
c+"') threw an exception: "+t.message)}return 0}catch(q){return"undefined"!==typeof U&&q instanceof L||u(q),-q.g}},___syscall118:function(a,b){V=b;try{return wc(),0}catch(c){return"undefined"!==typeof U&&c instanceof L||u(c),-c.g}},_nanosleep:function(a,b){var c=r[a>>2],d=r[a+4>>2];0!==b&&(r[b>>2]=0,r[b+4>>2]=0);return yc(1E6*c+d/1E3)},___syscall20:function(a,b){V=b;return 42},___syscall183:function(a,b){V=b;try{var c=X(),d=X();if(0===d)return-J.h;if(2>d)return-J.Qa;Ga("/",c);return c}catch(f){return"undefined"!==
typeof U&&f instanceof L||u(f),-f.g}},___assert_fail:function(a,b,c,d){oa=!0;throw"Assertion failed: "+w(a)+", at: "+[b?w(b):"unknown filename",c,d?w(d):"unknown function"]+" at "+Na();},_usleep:yc,___buildEnvironment:Fc,__addDays:Pc,_sqlite3CodeSubselect:function(){e.printErr("missing function: sqlite3CodeSubselect");u(-1)},___setErrNo:nb,___syscall197:function(a,b){V=b;try{var c=wc(),d=X();return vc(dc,c.path,d)}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.g}},___syscall196:function(a,
b){V=b;try{var c=Y(),d=X();return vc(ec,c,d)}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.g}},___syscall195:function(a,b){V=b;try{var c=Y(),d=X();return vc(dc,c,d)}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.g}},___syscall194:function(a,b){V=b;try{var c=X();assert(0===X());var d=X(),f=X();0<=d?assert(0===f):assert(-1===f);var g=P[c];if(!g)throw new L(J.B);if(0===(g.flags&2097155))throw new L(J.h);hc(g.c,d);return 0}catch(h){return"undefined"!==typeof U&&h instanceof
L||u(h),-h.g}},_sqlite3ExprForVectorField:function(){e.printErr("missing function: sqlite3ExprForVectorField");u(-1)},___syscall212:function(a,b){V=b;try{var c=Y();X();X();gc(c);return 0}catch(d){return"undefined"!==typeof U&&d instanceof L||u(d),-d.g}},_strftime:function(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&
0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function m(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function t(a){a=Pc(new Date(a.l+1900,0,1),a.$);var b=m(new Date(a.getFullYear()+1,0,4));return 0>=
h(m(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var q=r[d+40>>2];d={ub:r[d>>2],tb:r[d+4>>2],Z:r[d+8>>2],G:r[d+12>>2],A:r[d+16>>2],l:r[d+20>>2],Na:r[d+24>>2],$:r[d+28>>2],Td:r[d+32>>2],sb:r[d+36>>2],vb:q?w(q):""};c=w(c);var q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"},v;for(v in q)c=c.replace(new RegExp(v,"g"),q[v]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
C="January February March April May June July August September October November December".split(" "),q={"%a":function(a){return x[a.Na].substring(0,3)},"%A":function(a){return x[a.Na]},"%b":function(a){return C[a.A].substring(0,3)},"%B":function(a){return C[a.A]},"%C":function(a){return g((a.l+1900)/100|0,2)},"%d":function(a){return g(a.G,2)},"%e":function(a){return f(a.G,2," ")},"%g":function(a){return t(a).toString().substring(2)},"%G":function(a){return t(a)},"%H":function(a){return g(a.Z,2)},
"%I":function(a){a=a.Z;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.G+Mc(Lc(a.l+1900)?Nc:Oc,a.A-1),3)},"%m":function(a){return g(a.A+1,2)},"%M":function(a){return g(a.tb,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.Z&&12>a.Z?"AM":"PM"},"%S":function(a){return g(a.ub,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.l+1900,a.A+1,a.G,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.l+1900,0,1),c=0===b.getDay()?b:Pc(b,7-b.getDay());a=new Date(a.l+
1900,a.A,a.G);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Mc(Lc(a.getFullYear())?Nc:Oc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=m(new Date(a.l+1900,0,4)),c=m(new Date(a.l+1901,0,4)),d=Pc(new Date(a.l+1900,0,1),a.$);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.l+1900?a.$+32-b.getDate():a.$+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.l+1900,a.A+1,a.G,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.l,0,1),c=1===b.getDay()?
b:Pc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.l+1900,a.A,a.G);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Mc(Lc(a.getFullYear())?Nc:Oc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.l+1900).toString().substring(2)},"%Y":function(a){return a.l+1900},"%z":function(a){a=a.sb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.vb},"%%":function(){return"%"}};for(v in q)0<=c.indexOf(v)&&(c=c.replace(new RegExp(v,
"g"),q[v](d)));v=D(c,!1);if(v.length>b)return 0;sa(v,a);return v.length-1},___syscall94:function(a,b){V=b;try{var c=X(),d=X(),f=P[c];if(!f)throw new L(J.B);fc(f.c,d);return 0}catch(g){return"undefined"!==typeof U&&g instanceof L||u(g),-g.g}},__arraySum:Mc,_emscripten_memcpy_big:function(a,b,c){B.set(B.subarray(b,b+c),a);return a},_gmtime:function(a){return Dc(a,Bc)},_getenv:Hc,___syscall33:function(a,b){V=b;try{var c=Y(),d;var f=X();if(f&-8)d=-J.h;else{var g;g=R(c,{F:!0}).c;c="";f&4&&(c+="r");f&2&&
(c+="w");f&1&&(c+="x");d=c&&Pb(g,c)?-J.R:0}return d}catch(h){return"undefined"!==typeof U&&h instanceof L||u(h),-h.g}},___syscall15:function(a,b){V=b;try{var c=Y(),d=X();fc(c,d);return 0}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.g}},__isLeapYear:Lc,___syscall39:function(a,b){V=b;try{var c=Y(),d=X(),c=pb(c);"/"===c[c.length-1]&&(c=c.substr(0,c.length-1));T(c,d);return 0}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.g}},_sqlite3VectorFieldSubexpr:function(){e.printErr("missing function: sqlite3VectorFieldSubexpr");
u(-1)},___syscall10:function(a,b){V=b;try{var c=Y();cc(c);return 0}catch(d){return"undefined"!==typeof U&&d instanceof L||u(d),-d.g}},_gmtime_r:Dc,___syscall3:function(a,b){V=b;try{var c=wc(),d=X(),f=X();return mc(c,y,d,f)}catch(g){return"undefined"!==typeof U&&g instanceof L||u(g),-g.g}},___syscall202:Kc,___syscall6:function(a,b){V=b;try{var c=wc();kc(c);return 0}catch(d){return"undefined"!==typeof U&&d instanceof L||u(d),-d.g}},___syscall5:function(a,b){V=b;try{var c=Y(),d=X(),f=X();return ic(c,
d,f).fd}catch(g){return"undefined"!==typeof U&&g instanceof L||u(g),-g.g}},___syscall4:function(a,b){V=b;try{var c=wc(),d=X(),f=X();return nc(c,y,d,f)}catch(g){return"undefined"!==typeof U&&g instanceof L||u(g),-g.g}},_time:function(a){var b=Date.now()/1E3|0;a&&(r[a>>2]=b);return b},_gettimeofday:function(a){var b=Date.now();r[a>>2]=b/1E3|0;r[a+4>>2]=b%1E3*1E3|0;return 0},___syscall140:function(a,b){V=b;try{var c=wc();X();var d=X(),f=X(),g=X();lc(c,d,g);r[f>>2]=c.position;c.ja&&0===d&&0===g&&(c.ja=
null);return 0}catch(h){return"undefined"!==typeof U&&h instanceof L||u(h),-h.g}},___syscall207:function(a,b){V=b;try{var c=X();X();X();var d=P[c];if(!d)throw new L(J.B);gc(d.c);return 0}catch(f){return"undefined"!==typeof U&&f instanceof L||u(f),-f.g}},___syscall201:function(){return Kc.apply(null,arguments)},DYNAMICTOP_PTR:la,tempDoublePtr:lb,ABORT:oa,STACKTOP:l,STACK_MAX:Ua};var Qc=e.asm(e.Ua,e.Va,buffer);e.asm=Qc;e._sqlite3_value_blob=function(){return e.asm._sqlite3_value_blob.apply(null,arguments)};
e._sqlite3_column_name=function(){return e.asm._sqlite3_column_name.apply(null,arguments)};e._sqlite3_reset=function(){return e.asm._sqlite3_reset.apply(null,arguments)};e._sqlite3_column_type=function(){return e.asm._sqlite3_column_type.apply(null,arguments)};e._sqlite3_exec=function(){return e.asm._sqlite3_exec.apply(null,arguments)};e.stackSave=function(){return e.asm.stackSave.apply(null,arguments)};e._sqlite3_result_null=function(){return e.asm._sqlite3_result_null.apply(null,arguments)};
e._sqlite3_step=function(){return e.asm._sqlite3_step.apply(null,arguments)};e._sqlite3_prepare_v2=function(){return e.asm._sqlite3_prepare_v2.apply(null,arguments)};e._sqlite3_close_v2=function(){return e.asm._sqlite3_close_v2.apply(null,arguments)};e._sqlite3_open=function(){return e.asm._sqlite3_open.apply(null,arguments)};e._sqlite3_result_text=function(){return e.asm._sqlite3_result_text.apply(null,arguments)};
e._emscripten_get_global_libc=function(){return e.asm._emscripten_get_global_libc.apply(null,arguments)};e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};e._sqlite3_column_bytes=function(){return e.asm._sqlite3_column_bytes.apply(null,arguments)};e._sqlite3_bind_int=function(){return e.asm._sqlite3_bind_int.apply(null,arguments)};e._sqlite3_bind_blob=function(){return e.asm._sqlite3_bind_blob.apply(null,arguments)};
var xc=e._memset=function(){return e.asm._memset.apply(null,arguments)},Ic=e._sbrk=function(){return e.asm._sbrk.apply(null,arguments)};e._sqlite3_value_double=function(){return e.asm._sqlite3_value_double.apply(null,arguments)};var zc=e._memcpy=function(){return e.asm._memcpy.apply(null,arguments)};e._sqlite3_result_double=function(){return e.asm._sqlite3_result_double.apply(null,arguments)};e._sqlite3_value_text=function(){return e.asm._sqlite3_value_text.apply(null,arguments)};
e._sqlite3_changes=function(){return e.asm._sqlite3_changes.apply(null,arguments)};e._sqlite3_column_blob=function(){return e.asm._sqlite3_column_blob.apply(null,arguments)};e._sqlite3_bind_parameter_index=function(){return e.asm._sqlite3_bind_parameter_index.apply(null,arguments)};e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)};e._sqlite3_value_type=function(){return e.asm._sqlite3_value_type.apply(null,arguments)};
e.getTempRet0=function(){return e.asm.getTempRet0.apply(null,arguments)};e._sqlite3_column_text=function(){return e.asm._sqlite3_column_text.apply(null,arguments)};e.setTempRet0=function(){return e.asm.setTempRet0.apply(null,arguments)};e._sqlite3_value_bytes=function(){return e.asm._sqlite3_value_bytes.apply(null,arguments)};e._sqlite3_finalize=function(){return e.asm._sqlite3_finalize.apply(null,arguments)};e._sqlite3_column_double=function(){return e.asm._sqlite3_column_double.apply(null,arguments)};
e._sqlite3_create_function_v2=function(){return e.asm._sqlite3_create_function_v2.apply(null,arguments)};e._sqlite3_errmsg=function(){return e.asm._sqlite3_errmsg.apply(null,arguments)};e._sqlite3_value_int=function(){return e.asm._sqlite3_value_int.apply(null,arguments)};e._sqlite3_data_count=function(){return e.asm._sqlite3_data_count.apply(null,arguments)};e._sqlite3_bind_text=function(){return e.asm._sqlite3_bind_text.apply(null,arguments)};
e.stackRestore=function(){return e.asm.stackRestore.apply(null,arguments)};e._sqlite3_bind_double=function(){return e.asm._sqlite3_bind_double.apply(null,arguments)};var Ac=e._llvm_bswap_i32=function(){return e.asm._llvm_bswap_i32.apply(null,arguments)};e._RegisterExtensionFunctions=function(){return e.asm._RegisterExtensionFunctions.apply(null,arguments)};var Ma=e._free=function(){return e.asm._free.apply(null,arguments)};e.runPostSets=function(){return e.asm.runPostSets.apply(null,arguments)};
e.setThrew=function(){return e.asm.setThrew.apply(null,arguments)};e.establishStackSpace=function(){return e.asm.establishStackSpace.apply(null,arguments)};var Jc=e._memmove=function(){return e.asm._memmove.apply(null,arguments)};e._sqlite3_free=function(){return e.asm._sqlite3_free.apply(null,arguments)};e._sqlite3_clear_bindings=function(){return e.asm._sqlite3_clear_bindings.apply(null,arguments)};var Da=e._malloc=function(){return e.asm._malloc.apply(null,arguments)};
e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)};e.dynCall_viiiij=function(){return e.asm.dynCall_viiiij.apply(null,arguments)};e.dynCall_viiii=function(){return e.asm.dynCall_viiii.apply(null,arguments)};e.dynCall_i=function(){return e.asm.dynCall_i.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.dynCall_viji=function(){return e.asm.dynCall_viji.apply(null,arguments)};
e.dynCall_vii=function(){return e.asm.dynCall_vii.apply(null,arguments)};e.dynCall_iiiiiii=function(){return e.asm.dynCall_iiiiiii.apply(null,arguments)};e.dynCall_ii=function(){return e.asm.dynCall_ii.apply(null,arguments)};e.dynCall_iiiij=function(){return e.asm.dynCall_iiiij.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.dynCall_viii.apply(null,arguments)};e.dynCall_iiji=function(){return e.asm.dynCall_iiji.apply(null,arguments)};
e.dynCall_iiiii=function(){return e.asm.dynCall_iiiii.apply(null,arguments)};e.dynCall_iijii=function(){return e.asm.dynCall_iijii.apply(null,arguments)};e.dynCall_iii=function(){return e.asm.dynCall_iii.apply(null,arguments)};e.dynCall_iiiiii=function(){return e.asm.dynCall_iiiiii.apply(null,arguments)};e.dynCall_iij=function(){return e.asm.dynCall_iij.apply(null,arguments)};n.v=e.stackAlloc;n.X=e.stackSave;n.Q=e.stackRestore;n.Dd=e.establishStackSpace;n.qb=e.setTempRet0;n.hb=e.getTempRet0;
e.asm=Qc;
if(G)if("function"===typeof e.locateFile?G=e.locateFile(G):e.memoryInitializerPrefixURL&&(G=e.memoryInitializerPrefixURL+G),k||fa){var Rc=e.readBinary(G);B.set(Rc,n.da)}else{var Tc=function(){e.readAsync(G,Sc,function(){throw"could not load memory initializer "+G;})};jb();var Sc=function(a){a.byteLength&&(a=new Uint8Array(a));B.set(a,n.da);e.memoryInitializerRequest&&delete e.memoryInitializerRequest.response;kb()};if(e.memoryInitializerRequest){var Uc=function(){var a=e.memoryInitializerRequest;200!==
a.status&&0!==a.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+a.status+", retrying "+G),Tc()):Sc(a.response)};e.memoryInitializerRequest.response?setTimeout(Uc,0):e.memoryInitializerRequest.addEventListener("load",Uc)}else Tc()}function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ka.prototype=Error();ka.prototype.constructor=ka;
var Vc=null,ib=function Wc(){e.calledRun||Xc();e.calledRun||(ib=Wc)};e.callMain=e.Ad=function(a){function b(){for(var a=0;3>a;a++)d.push(0)}a=a||[];Fa||(Fa=!0,Xa(Za));var c=a.length+1,d=[z(D(e.thisProgram),"i8",0)];b();for(var f=0;f<c-1;f+=1)d.push(z(D(a[f]),"i8",0)),b();d.push(0);d=z(d,"i32",0);try{var g=e._main(c,d,0);Yc(g,!0)}catch(h){h instanceof ka||("SimulateInfiniteLoop"==h?e.noExitRuntime=!0:((a=h)&&"object"===typeof h&&h.stack&&(a=[h,h.stack]),e.W("exception thrown: "+a),e.quit(1,h)))}finally{}};
function Xc(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!oa)){Fa||(Fa=!0,Xa(Za));Xa($a);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&Zc&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)db(e.postRun.shift());Xa(bb)}}a=a||e.arguments;null===Vc&&(Vc=Date.now());if(!(0<gb)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)cb(e.preRun.shift());Xa(Ya);0<gb||e.calledRun||(e.setStatus?(e.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=e.run=Xc;function Yc(a,b){if(!b||!e.noExitRuntime){if(!e.noExitRuntime&&(oa=!0,l=void 0,Xa(ab),e.onExit))e.onExit(a);k&&process.exit(a);e.quit(a,new ka(a))}}e.exit=e.exit=Yc;var $c=[];
function u(a){void 0!==a?(e.print(a),e.W(a),a=JSON.stringify(a)):a="";oa=!0;var b="abort("+a+") at "+Na()+"\nIf this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.";$c&&$c.forEach(function(c){b=c(b,a)});throw b;}e.abort=e.abort=u;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Zc=!0;e.noInitialRun&&(Zc=!1);e.noExitRuntime=!0;Xc();
var Database,ad,bd,Z,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd=window.Ra||{};
e.onRuntimeInitialized=function(){n=e.Runtime;Z=n.v(4);bd=function(){function a(a,c){this.j=a;this.db=c;this.t=1;this.fa=[]}a.prototype.bind=function(a){if(!this.j)throw"Statement closed";this.reset();return Array.isArray(a)?this.Xa(a):this.Ya(a)};a.prototype.step=function(){var a;if(!this.j)throw"Statement closed";this.t=1;switch(a=Cd(this.j)){case 100:return!0;case 101:return!1;default:return this.db.handleError(a)}};a.prototype.fb=function(a){null==a&&(a=this.t++);return md(this.j,a)};a.prototype.gb=
function(a){null==a&&(a=this.t++);return od(this.j,a)};a.prototype.getBlob=function(a){var c,d,f,g;null==a&&(a=this.t++);g=ld(this.j,a);d=kd(this.j,a);f=new Uint8Array(g);for(a=c=0;0<=g?c<g:c>g;a=0<=g?++c:--c)f[a]=y[d+a];return f};a.prototype.get=function(a){var c,d,f;null!=a&&this.bind(a)&&this.step();f=[];a=c=0;for(d=rd(this.j);0<=d?c<d:c>d;a=0<=d?++c:--c)switch(pd(this.j,a)){case 1:case 2:f.push(this.fb(a));break;case 3:f.push(this.gb(a));break;case 4:f.push(this.getBlob(a));break;default:f.push(null)}return f};
a.prototype.getColumnNames=function(){var a,c,d,f;f=[];a=c=0;for(d=rd(this.j);0<=d?c<d:c>d;a=0<=d?++c:--c)f.push(nd(this.j,a));return f};a.prototype.getAsObject=function(a){var c,d,f,g,h,m;m=this.get(a);g=this.getColumnNames();h={};a=c=0;for(d=g.length;c<d;a=++c)f=g[a],h[f]=m[a];return h};a.prototype.run=function(a){null!=a&&this.bind(a);this.step();return this.reset()};a.prototype.ab=function(a,c){var d,f;null==c&&(c=this.t++);d=D(a);this.fa.push(f=z(d,"i8",0));this.db.handleError(gd(this.j,c,f,
d.length-1,0))};a.prototype.Wa=function(a,c){var d;null==c&&(c=this.t++);this.fa.push(d=z(a,"i8",0));this.db.handleError(cd(this.j,c,d,a.length,0))};a.prototype.$a=function(a,c){null==c&&(c=this.t++);this.db.handleError((a===(a|0)?ed:dd)(this.j,c,a))};a.prototype.Za=function(a){null==a&&(a=this.t++);cd(this.j,a,0,0,0)};a.prototype.ya=function(a,c){null==c&&(c=this.t++);switch(typeof a){case "string":this.ab(a,c);break;case "number":case "boolean":this.$a(a+0,c);break;case "object":if(null===a){this.Za(c);
break}if(null!=a.length){this.Wa(a,c);break}throw"Wrong API use : tried to bind a value of an unknown type ("+a+").";}};a.prototype.Ya=function(a){var c,d,f;for(c in a)f=a[c],d=fd(this.j,c),0!==d&&this.ya(f,d);return!0};a.prototype.Xa=function(a){var c,d,f,g;f=c=0;for(d=a.length;c<d;f=++c)g=a[f],this.ya(g,f+1);return!0};a.prototype.reset=function(){this.freemem();return 0===id(this.j)&&0===yd(this.j)};a.prototype.freemem=function(){for(var a;a=this.fa.pop();)Ma(a);return null};a.prototype.free=function(){var a;
this.freemem();a=0===ud(this.j);delete this.db.Y[this.j];this.j=0;return a};return a}();Database=function(){function a(a){this.filename="dbfile_"+(4294967295*Math.random()>>>0);null!=a&&sc("/",this.filename,a,!0,!0);this.handleError(vd(this.filename,Z));this.db=Ca(Z,"i32");ad(this.db);this.Y={}}a.prototype.run=function(a,c){var d;if(!this.db)throw"Database closed";c?(d=this.prepare(a,c),d.step(),d.free()):this.handleError(td(this.db,a,0,0,Z));return this};a.prototype.exec=function(a){var c,d,f,g,
h;if(!this.db)throw"Database closed";g=n.X();n.v(a.length<<3);f=a.length<<3;d=n.v(f);ta(a,d,f);a=n.v(4);for(f=[];0!==Ca(d,"i8");)if(ua(Z,0,"i32"),ua(a,0,"i32"),this.handleError(xd(this.db,d,-1,Z,a)),c=Ca(Z,"i32"),d=Ca(a,"i32"),0!==c){h=new bd(c,this);for(c=null;h.step();)null===c&&(c={columns:h.getColumnNames(),values:[]},f.push(c)),c.values.push(h.get());h.free()}n.Q(g);return f};a.prototype.each=function(a,c,d,f){"function"===typeof c&&(f=d,d=c,c=void 0);for(a=this.prepare(a,c);a.step();)d(a.getAsObject());
a.free();if("function"===typeof f)return f()};a.prototype.prepare=function(a,c){var d,f;ua(Z,0,"i32");this.handleError(wd(this.db,a,-1,Z,0));d=Ca(Z,"i32");if(0===d)throw"Nothing to prepare";f=new bd(d,this);null!=c&&f.bind(c);return this.Y[d]=f};a.prototype["export"]=function(){var a,c,d,f;d=this.Y;for(a in d)f=d[a],f.free();this.handleError(jd(this.db));f=this.filename;a=a={encoding:"binary"};a.flags=a.flags||"r";a.encoding=a.encoding||"binary";if("utf8"!==a.encoding&&"binary"!==a.encoding)throw Error('Invalid encoding type "'+
a.encoding+'"');d=ic(f,a.flags);f=dc(f).size;var g=new Uint8Array(f);mc(d,g,0,f,0);"utf8"===a.encoding?c=Ia(g,0):"binary"===a.encoding&&(c=g);kc(d);this.handleError(vd(this.filename,Z));this.db=Ca(Z,"i32");return c};a.prototype.close=function(){var a,c,d;c=this.Y;for(a in c)d=c[a],d.free();this.handleError(jd(this.db));cc("/"+this.filename);return this.db=null};a.prototype.handleError=function(a){if(0===a)return null;a=sd(this.db);throw Error(a);};a.prototype.getRowsModified=function(){return hd(this.db)};
a.prototype.create_function=function(a,c){var d;d=n.ua(function(a,b,d){var m,t,q,v,x;t=[];for(m=q=0;0<=b?q<=b:q>=b;m=0<=b?++q:--q)v=Ca(d+4*m,"i32"),x=Id(v),m=function(){switch(!1){case 1!==x:return Gd;case 2!==x:return Fd;case 3!==x:return Hd;case 4!==x:return function(a){var b,c,d,f;f=Ed(a);b=Dd(a);a=new Uint8Array(f);for(c=d=0;0<=f?d<f:d>f;c=0<=f?++d:--d)a[c]=y[b+c];return a};default:return function(){return null}}}(),m=m(v),t.push(m);if(b=c.apply(null,t))switch(typeof b){case "number":return zd(a,
b);case "string":return Bd(a,b,-1,-1)}else return Ad(a)});this.handleError(qd(this.db,a,c.length,1,0,d,0,0,0));return this};return a}();vd=e.cwrap("sqlite3_open","number",["string","number"]);jd=e.cwrap("sqlite3_close_v2","number",["number"]);td=e.cwrap("sqlite3_exec","number",["number","string","number","number","number"]);e.cwrap("sqlite3_free","",["number"]);hd=e.cwrap("sqlite3_changes","number",["number"]);wd=e.cwrap("sqlite3_prepare_v2","number",["number","string","number","number","number"]);
xd=e.cwrap("sqlite3_prepare_v2","number",["number","number","number","number","number"]);gd=e.cwrap("sqlite3_bind_text","number",["number","number","number","number","number"]);cd=e.cwrap("sqlite3_bind_blob","number",["number","number","number","number","number"]);dd=e.cwrap("sqlite3_bind_double","number",["number","number","number"]);ed=e.cwrap("sqlite3_bind_int","number",["number","number","number"]);fd=e.cwrap("sqlite3_bind_parameter_index","number",["number","string"]);Cd=e.cwrap("sqlite3_step",
"number",["number"]);sd=e.cwrap("sqlite3_errmsg","string",["number"]);rd=e.cwrap("sqlite3_data_count","number",["number"]);md=e.cwrap("sqlite3_column_double","number",["number","number"]);od=e.cwrap("sqlite3_column_text","string",["number","number"]);kd=e.cwrap("sqlite3_column_blob","number",["number","number"]);ld=e.cwrap("sqlite3_column_bytes","number",["number","number"]);pd=e.cwrap("sqlite3_column_type","number",["number","number"]);nd=e.cwrap("sqlite3_column_name","string",["number","number"]);
yd=e.cwrap("sqlite3_reset","number",["number"]);id=e.cwrap("sqlite3_clear_bindings","number",["number"]);ud=e.cwrap("sqlite3_finalize","number",["number"]);qd=e.cwrap("sqlite3_create_function_v2","number","number string number number number number number number number".split(" "));Id=e.cwrap("sqlite3_value_type","number",["number"]);Ed=e.cwrap("sqlite3_value_bytes","number",["number"]);Hd=e.cwrap("sqlite3_value_text","string",["number"]);Gd=e.cwrap("sqlite3_value_int","number",["number"]);Dd=e.cwrap("sqlite3_value_blob",
"number",["number"]);Fd=e.cwrap("sqlite3_value_double","number",["number"]);zd=e.cwrap("sqlite3_result_double","",["number","number"]);Ad=e.cwrap("sqlite3_result_null","",["number"]);Bd=e.cwrap("sqlite3_result_text","",["number","string","number","number"]);ad=e.cwrap("RegisterExtensionFunctions","number",["number"]);this.SQL={Database:Database};e.Ra=Jd;"function"===typeof Jd.lb&&Jd.lb()}.bind(this);if("undefined"!==typeof module)e.onRuntimeInitialized();
return this['SQL'];
})();
if (typeof module !== 'undefined') module.exports = SQL;
if (typeof define === 'function') define(SQL);
