// This prevents pollution of the global namespace
var SQL = (function () {
  var Module = window.Module;
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa={},h;for(h in e)e.hasOwnProperty(h)&&(aa[h]=e[h]);var l=!1,m=!1,p=!1,ba=!1;
if(e.ENVIRONMENT)if("WEB"===e.ENVIRONMENT)l=!0;else if("WORKER"===e.ENVIRONMENT)m=!0;else if("NODE"===e.ENVIRONMENT)p=!0;else if("SHELL"===e.ENVIRONMENT)ba=!0;else throw Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.");else l="object"===typeof window,m="function"===typeof importScripts,p="object"===typeof process&&"function"===typeof require&&!l&&!m,ba=!l&&!p&&!m;
if(p){e.print||(e.print=console.log);e.printErr||(e.printErr=console.warn);var ca,da;e.read=function(a,b){ca||(ca=require("fs"));da||(da=require("path"));a=da.normalize(a);a=ca.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};e.thisProgram||(e.thisProgram=1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=
e);process.on("uncaughtException",function(a){if(!(a instanceof ea))throw a;});process.on("unhandledRejection",function(){process.exit(1)});e.inspect=function(){return"[Emscripten Module object]"}}else if(ba)e.print||(e.print=print),"undefined"!=typeof printErr&&(e.printErr=printErr),e.read="undefined"!=typeof read?function(a){return read(a)}:function(){throw"no read() available";},e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===
typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(l||m)e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},"undefined"!=typeof arguments&&(e.arguments=arguments),"undefined"!==typeof console?(e.print||(e.print=function(a){console.log(a)}),e.printErr||(e.printErr=function(a){console.warn(a)})):e.print||(e.print=function(){}),"undefined"===typeof e.setWindowTitle&&(e.setWindowTitle=function(a){document.title=a});else throw Error("Unknown runtime environment. Where are we?");
e.print||(e.print=function(){});e.printErr||(e.printErr=e.print);e.arguments||(e.arguments=[]);e.thisProgram||(e.thisProgram="./this.program");e.quit||(e.quit=function(a,b){throw b;});e.print=e.print;e.printErr=e.printErr;e.preRun=[];e.postRun=[];for(h in aa)aa.hasOwnProperty(h)&&(e[h]=aa[h]);aa=void 0;function fa(a){assert(!ha);var b=q;q=q+a+15&-16;return b}function ia(a){assert(r);var b=t[r>>2];a=b+a+15&-16;t[r>>2]=a;if(a=a>=u)ja(),a=!0;return a?(t[r>>2]=b,0):b}
function ka(a){var b;b||(b=16);return Math.ceil(a/b)*b}var w=Array(64),la=0;function assert(a,b){a||x("Assertion failed: "+b)}
function oa(a){var b="i32";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":z[a>>0]=0;break;case "i8":z[a>>0]=0;break;case "i16":pa[a>>1]=0;break;case "i32":t[a>>2]=0;break;case "i64":tempI64=[0,(tempDouble=0,1<=+qa(tempDouble)?0<tempDouble?(ra(+sa(tempDouble/4294967296),4294967295)|0)>>>0:~~+ta((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];t[a>>2]=tempI64[0];t[a+4>>2]=tempI64[1];break;case "float":ua[a>>2]=0;break;case "double":va[a>>3]=0;break;default:x("invalid type for setValue: "+
b)}}function A(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return z[a>>0];case "i8":return z[a>>0];case "i16":return pa[a>>1];case "i32":return t[a>>2];case "i64":return t[a>>2];case "float":return ua[a>>2];case "double":return va[a>>3];default:x("invalid type for getValue: "+b)}return null}
function wa(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;b=4==b?f:["function"===typeof xa?xa:fa,ya,fa,ia][void 0===b?2:b](Math.max(d,1));if(c){var f=b;assert(0==(b&3));for(a=b+(d&-4);f<a;f+=4)t[f>>2]=0;for(a=b+d;f<a;)z[f++>>0]=0;return b}a.subarray||a.slice?B.set(a,b):B.set(new Uint8Array(a),b);return b}
function C(a){var b;if(0===b||!a)return"";for(var c=0,d,f=0;;){d=B[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,B.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return za(B,a)}var Aa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function za(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&Aa)return Aa.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var k=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|k;else{var n=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|k<<6|n;else{var G=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|k<<12|n<<6|G}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function Ba(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);55296<=k&&57343>=k&&(k=65536+((k&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(2097151>=k){if(c+3>=d)break;b[c++]=240|k>>18}else{if(67108863>=k){if(c+4>=d)break;b[c++]=248|k>>24}else{if(c+5>=d)break;b[c++]=252|k>>30;b[c++]=128|k>>24&63}b[c++]=128|k>>18&63}b[c++]=128|
k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Da(a){return a.replace(/__Z[\w\d_]+/g,function(a){return a===a?a:a+" ["+a+"]"})}var buffer,z,B,pa,t,ua,va;
function Ea(){e.HEAP8=z=new Int8Array(buffer);e.HEAP16=pa=new Int16Array(buffer);e.HEAP32=t=new Int32Array(buffer);e.HEAPU8=B=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=ua=new Float32Array(buffer);e.HEAPF64=va=new Float64Array(buffer)}var Fa,q,ha,Ga,Ha,Ia,Ja,r;Fa=q=Ga=Ha=Ia=Ja=r=0;ha=!1;
function ja(){x("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+u+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ka=e.TOTAL_STACK||5242880,u=e.TOTAL_MEMORY||16777216;u<Ka&&e.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+u+"! (TOTAL_STACK="+Ka+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:u/65536,maximum:u/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(u),e.buffer=buffer);Ea();t[0]=1668509029;pa[1]=25459;if(115!==B[2]||99!==B[3])throw"Runtime error: expected the system to be little-endian!";
function La(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.ad;"number"===typeof c?void 0===b.da?e.dynCall_v(c):e.dynCall_vi(c,b.da):c(void 0===b.da?null:b.da)}}}var Ma=[],Na=[],Oa=[],Pa=[],Qa=[],Ra=!1;function Sa(){var a=e.preRun.shift();Ma.unshift(a)}var qa=Math.abs,ta=Math.ceil,sa=Math.floor,ra=Math.min,D=0,Ta=null,Ua=null;e.preloadedImages={};e.preloadedAudios={};
function Va(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(y){x(y)}}function b(){return e.wasmBinary||!l&&!m||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){n=a.exports;if(n.memory){a=n.memory;var b=e.buffer;a.byteLength<b.byteLength&&e.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;Ea()}e.asm=n;e.usingWasm=!0;D--;e.monitorRunDependencies&&e.monitorRunDependencies(D);0==D&&(null!==Ta&&(clearInterval(Ta),Ta=null),Ua&&(a=Ua,Ua=null,a()))}
function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,k)}).then(a).catch(function(a){e.printErr("failed to asynchronously prepare wasm: "+a);x(a)})}if("object"!==typeof WebAssembly)return e.printErr("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return e.printErr("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;k.global={NaN:NaN,Infinity:Infinity};k["global.Math"]=Math;k.env=a;D++;e.monitorRunDependencies&&e.monitorRunDependencies(D);
if(e.instantiateWasm)try{return e.instantiateWasm(k,c)}catch(gb){return e.printErr("Module.instantiateWasm callback failed with error: "+gb),!1}e.wasmBinary||"function"!==typeof WebAssembly.Qa||Va(f)||"function"!==typeof fetch?g(d):WebAssembly.Qa(fetch(f,{credentials:"same-origin"}),k).then(d).catch(function(a){e.printErr("wasm streaming compile failed: "+a);e.printErr("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="sql-optimized-wasm-raw.wast",f="sql-optimized-wasm-raw.wasm",
g="sql-optimized-wasm-raw.temp.asm.js";"function"===typeof e.locateFile&&(Va(d)||(d=e.locateFile(d)),Va(f)||(f=e.locateFile(f)),Va(g)||(g=e.locateFile(g)));var k={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:e},n=null;e.asmPreload=e.asm;var G=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===v)var b=G(a);else a:{var c=e.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-
c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(Cb){b=null;break a}b=void 0}return b};var v="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=
0);(b=c(b))||x("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();Fa=1024;q=Fa+25664;Na.push();e.STATIC_BASE=Fa;e.STATIC_BUMP=25664;q+=16;
var E={B:1,A:2,Lc:3,Hb:4,T:5,na:6,$a:7,ec:8,G:9,ob:10,ka:11,Vc:11,Ca:12,S:13,Ab:14,rc:15,N:16,la:17,Wc:18,aa:19,U:20,O:21,i:22,$b:23,Ba:24,wc:25,Sc:26,Bb:27,nc:28,V:29,Ic:30,Tb:31,Cc:32,xb:33,Da:34,jc:42,Eb:43,pb:44,Kb:45,Lb:46,Mb:47,Sb:48,Tc:49,cc:50,Jb:51,ub:35,fc:37,gb:52,jb:53,Xc:54,ac:55,kb:56,lb:57,vb:35,mb:59,pc:60,dc:61,Pc:62,oc:63,kc:64,lc:65,Hc:66,hc:67,cb:68,Mc:69,qb:70,Dc:71,Vb:72,yb:73,ib:74,xc:76,hb:77,Gc:78,Nb:79,Ob:80,Rb:81,Qb:82,Pb:83,qc:38,ma:39,Wb:36,$:40,yc:95,Bc:96,tb:104,bc:105,
eb:97,Fc:91,uc:88,mc:92,Jc:108,sb:111,ab:98,rb:103,Zb:101,Xb:100,Qc:110,Cb:112,Db:113,Gb:115,fb:114,wb:89,Ub:90,Ec:93,Kc:94,bb:99,Yb:102,Ib:106,sc:107,Rc:109,Uc:87,zb:122,Nc:116,vc:95,ic:123,Fb:84,zc:75,nb:125,tc:131,Ac:130,Oc:86},Wa={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function Xa(a){e.___errno_location&&(t[e.___errno_location()>>2]=a);return a}
function Ya(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Za(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ya(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function $a(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ab(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function bb(){var a=Array.prototype.slice.call(arguments,0);return Za(a.join("/"))}function F(a,b){return Za(a+"/"+b)}
function cb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ya(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var db=[];function eb(a,b){db[a]={input:[],output:[],M:b};fb(a,hb)}
var hb={open:function(a){var b=db[a.node.rdev];if(!b)throw new H(E.aa);a.tty=b;a.seekable=!1},close:function(a){a.tty.M.flush(a.tty)},flush:function(a){a.tty.M.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.M.va)throw new H(E.na);for(var f=0,g=0;g<d;g++){try{var k=a.tty.M.va(a.tty)}catch(n){throw new H(E.T);}if(void 0===k&&0===f)throw new H(E.ka);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.M.ha)throw new H(E.na);
for(var f=0;f<d;f++)try{a.tty.M.ha(a.tty,b[c+f])}catch(g){throw new H(E.T);}d&&(a.node.timestamp=Date.now());return f}},jb={va:function(a){if(!a.input.length){var b=null;if(p){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(k){}}try{d=fs.readSync(f,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))d=0;else throw k;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ib(b,!0)}return a.input.shift()},ha:function(a,b){null===b||10===b?(e.print(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(e.print(za(a.output,0)),a.output=[])}},kb={ha:function(a,b){null===b||10===b?(e.printErr(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(e.printErr(za(a.output,0)),a.output=[])}},I={v:null,o:function(){return I.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(E.B);I.v||(I.v={dir:{node:{u:I.c.u,l:I.c.l,lookup:I.c.lookup,P:I.c.P,rename:I.c.rename,unlink:I.c.unlink,rmdir:I.c.rmdir,readdir:I.c.readdir,symlink:I.c.symlink},stream:{D:I.f.D}},file:{node:{u:I.c.u,l:I.c.l},stream:{D:I.f.D,read:I.f.read,write:I.f.write,oa:I.f.oa,wa:I.f.wa,za:I.f.za}},link:{node:{u:I.c.u,
l:I.c.l,readlink:I.c.readlink},stream:{}},qa:{node:{u:I.c.u,l:I.c.l},stream:lb}});c=mb(a,b,c,d);J(c.mode)?(c.c=I.v.dir.node,c.f=I.v.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=I.v.file.node,c.f=I.v.file.stream,c.h=0,c.b=null):40960===(c.mode&61440)?(c.c=I.v.link.node,c.f=I.v.link.stream):8192===(c.mode&61440)&&(c.c=I.v.qa.node,c.f=I.v.qa.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Na:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.h;++c)b.push(a.b[c]);return b}return a.b},bd:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.h):new Uint8Array(a.b):new Uint8Array},ra:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=I.Na(a),a.h=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.h&&a.b.set(c.subarray(0,a.h),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Sa:function(a,b){if(a.h!=b)if(0==b)a.b=null,a.h=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.h)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.h=b}},c:{u:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.h:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.H=4096;b.blocks=Math.ceil(b.size/b.H);return b},
l:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.Sa(a,b.size)},lookup:function(){throw nb[E.A];},P:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(J(a.mode)){try{var d=K(b,c)}catch(g){}if(d)for(var f in d.b)throw new H(E.ma);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=K(a,b),d;for(d in c.b)throw new H(E.ma);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(E.i);return a.link}},f:{read:function(a,b,c,d,f){var g=a.node.b;if(f>=a.node.h)return 0;a=Math.min(a.node.h-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.h=d;if(0===a.h&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.h=d;if(f+d<=a.h)return a.b.set(b.subarray(c,c+d),f),d}I.ra(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.h=Math.max(a.h,f+d);return d},D:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.h);if(0>b)throw new H(E.i);return b},oa:function(a,b,c){I.ra(a.node,b+c);a.node.h=Math.max(a.node.h,
b+c)},wa:function(a,b,c,d,f,g,k){if(32768!==(a.node.mode&61440))throw new H(E.aa);c=a.node.b;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.h)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=xa(d);if(!d)throw new H(E.Ca);b.set(c,d)}else a=!1,d=c.byteOffset;return{cd:d,$c:a}},za:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new H(E.aa);if(f&2)return 0;I.f.write(a,b,0,d,c,!1);return 0}}},L={W:!1,Ua:function(){L.W=!!process.platform.match(/^win/)},
o:function(a){assert(p);return L.createNode(null,"/",L.ua(a.ga.root),0)},createNode:function(a,b,c){if(!J(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new H(E.i);a=mb(a,b,c);a.c=L.c;a.f=L.f;return a},ua:function(a){try{var b=fs.lstatSync(a);L.W&&(b.mode=b.mode|(b.mode&146)>>1)}catch(c){if(!c.code)throw c;throw new H(E[c.code]);}return b.mode},s:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.o.ga.root);b.reverse();return bb.apply(null,b)},sa:{0:"r",1:"r+",2:"r+",64:"r",
65:"r+",66:"r+",129:"rx+",193:"rx+",514:"w+",577:"w",578:"w+",705:"wx",706:"wx+",1024:"a",1025:"a",1026:"a+",1089:"a",1090:"a+",1153:"ax",1154:"ax+",1217:"ax",1218:"ax+",4096:"rs",4098:"rs+"},Ma:function(a){a&=-2656257;if(a in L.sa)return L.sa[a];throw new H(E.i);},c:{u:function(a){a=L.s(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new H(E[c.code]);}L.W&&!b.H&&(b.H=4096);L.W&&!b.blocks&&(b.blocks=(b.size+b.H-1)/b.H|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,
gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,H:b.H,blocks:b.blocks}},l:function(a,b){var c=L.s(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new H(E[d.code]);}},lookup:function(a,b){var c=F(L.s(a),b);c=L.ua(c);return L.createNode(a,b,c)},P:function(a,b,c,d){a=L.createNode(a,b,c,d);b=L.s(a);try{J(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;
throw new H(E[f.code]);}return a},rename:function(a,b,c){a=L.s(a);b=F(L.s(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new H(E[d.code]);}},unlink:function(a,b){a=F(L.s(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new H(E[c.code]);}},rmdir:function(a,b){a=F(L.s(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new H(E[c.code]);}},readdir:function(a){a=L.s(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new H(E[b.code]);}},symlink:function(a,
b,c){a=F(L.s(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new H(E[d.code]);}},readlink:function(a){var b=L.s(a);try{return b=fs.readlinkSync(b),b=ob.relative(ob.resolve(a.o.ga.root),b)}catch(c){if(!c.code)throw c;throw new H(E[c.code]);}}},f:{open:function(a){var b=L.s(a.node);try{32768===(a.node.mode&61440)&&(a.R=fs.openSync(b,L.Ma(a.flags)))}catch(c){if(!c.code)throw c;throw new H(E[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.R&&fs.closeSync(a.R)}catch(b){if(!b.code)throw b;
throw new H(E[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;b=Buffer.from?Buffer.from(b.buffer):new Buffer(b.buffer);try{return fs.readSync(a.R,b,c,d,f)}catch(g){throw new H(E[g.code]);}},write:function(a,b,c,d,f){b=Buffer.from?Buffer.from(b.buffer):new Buffer(b.buffer);try{return fs.writeSync(a.R,b,c,d,f)}catch(g){throw new H(E[g.code]);}},D:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.R).size}catch(d){throw new H(E[d.code]);}if(0>
b)throw new H(E.i);return b}}};q+=16;q+=16;q+=16;var pb=null,qb=[null],M=[],rb=1,N=null,sb=!0,O={},H=null,nb={};
function P(a,b){a=cb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ta:!0,ia:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ia)throw new H(E.$);a=Ya(a.split("/").filter(function(a){return!!a}),!1);var f=pb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=K(f,a[d]);c=F(c,a[d]);f.K&&(!g||g&&b.ta)&&(f=f.K.root);if(!g||b.I)for(g=0;40960===(f.mode&61440);)if(f=tb(c),c=cb($a(c),f),f=P(c,{ia:b.ia}).node,40<g++)throw new H(E.$);}return{path:c,node:f}}
function ub(a){for(var b;;){if(a===a.parent)return a=a.o.ya,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function vb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%N.length}function wb(a){var b=vb(a.parent.id,a.name);a.L=N[b];N[b]=a}function xb(a){var b=vb(a.parent.id,a.name);if(N[b]===a)N[b]=a.L;else for(b=N[b];b;){if(b.L===a){b.L=a.L;break}b=b.L}}
function K(a,b){var c;if(c=(c=yb(a,"x"))?c:a.c.lookup?0:E.S)throw new H(c,a);for(c=N[vb(a.id,b)];c;c=c.L){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function mb(a,b,c,d){zb||(zb=function(a,b,c,d){a||(a=this);this.parent=a;this.o=a.o;this.K=null;this.id=rb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},zb.prototype={},Object.defineProperties(zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new zb(a,b,c,d);wb(a);return a}function J(a){return 16384===(a&61440)}
var Ab={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Bb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yb(a,b){if(sb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return E.S}else return E.S;return 0}function Db(a,b){try{return K(a,b),E.la}catch(c){}return yb(a,"wx")}
function Eb(a,b,c){try{var d=K(a,b)}catch(f){return f.g}if(a=yb(a,"wx"))return a;if(c){if(!J(d.mode))return E.U;if(d===d.parent||"/"===ub(d))return E.N}else if(J(d.mode))return E.O;return 0}function Fb(a){var b=4096;for(a=a||0;a<=b;a++)if(!M[a])return a;throw new H(E.Ba);}
function Gb(a,b){Hb||(Hb=function(){},Hb.prototype={},Object.defineProperties(Hb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Hb,d;for(d in a)c[d]=a[d];a=c;b=Fb(b);a.fd=b;return M[b]=a}var lb={open:function(a){a.f=qb[a.node.rdev].f;a.f.open&&a.f.open(a)},D:function(){throw new H(E.V);}};function fb(a,b){qb[a]={f:b}}
function Ib(a,b){var c="/"===b,d=!b;if(c&&pb)throw new H(E.N);if(!c&&!d){var f=P(b,{ta:!1});b=f.path;f=f.node;if(f.K)throw new H(E.N);if(!J(f.mode))throw new H(E.U);}b={type:a,ga:{},ya:b,Ra:[]};a=a.o(b);a.o=b;b.root=a;c?pb=a:f&&(f.K=b,f.o&&f.o.Ra.push(b))}function Jb(a,b,c){var d=P(a,{parent:!0}).node;a=ab(a);if(!a||"."===a||".."===a)throw new H(E.i);var f=Db(d,a);if(f)throw new H(f);if(!d.c.P)throw new H(E.B);return d.c.P(d,a,b,c)}function Q(a,b){Jb(a,(void 0!==b?b:511)&1023|16384,0)}
function Kb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Jb(a,b|8192,c)}function Lb(a,b){if(!cb(a))throw new H(E.A);var c=P(b,{parent:!0}).node;if(!c)throw new H(E.A);b=ab(b);var d=Db(c,b);if(d)throw new H(d);if(!c.c.symlink)throw new H(E.B);c.c.symlink(c,b,a)}
function Mb(a){var b=P(a,{parent:!0}).node,c=ab(a),d=K(b,c),f=Eb(b,c,!1);if(f)throw new H(f);if(!b.c.unlink)throw new H(E.B);if(d.K)throw new H(E.N);try{O.willDeletePath&&O.willDeletePath(a)}catch(g){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.c.unlink(b,c);xb(d);try{if(O.onDeletePath)O.onDeletePath(a)}catch(g){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}}
function tb(a){a=P(a).node;if(!a)throw new H(E.A);if(!a.c.readlink)throw new H(E.i);return cb(ub(a.parent),a.c.readlink(a))}function Nb(a,b){a=P(a,{I:!b}).node;if(!a)throw new H(E.A);if(!a.c.u)throw new H(E.B);return a.c.u(a)}function Ob(a){return Nb(a,!0)}function Pb(a,b){var c;"string"===typeof a?c=P(a,{I:!0}).node:c=a;if(!c.c.l)throw new H(E.B);c.c.l(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Qb(a){var b;"string"===typeof a?b=P(a,{I:!0}).node:b=a;if(!b.c.l)throw new H(E.B);b.c.l(b,{timestamp:Date.now()})}function Rb(a,b){if(0>b)throw new H(E.i);var c;"string"===typeof a?c=P(a,{I:!0}).node:c=a;if(!c.c.l)throw new H(E.B);if(J(c.mode))throw new H(E.O);if(32768!==(c.mode&61440))throw new H(E.i);if(a=yb(c,"w"))throw new H(a);c.c.l(c,{size:b,timestamp:Date.now()})}
function R(a,b,c,d){if(""===a)throw new H(E.A);if("string"===typeof b){var f=Ab[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Za(a);try{g=P(a,{I:!(b&131072)}).node}catch(k){}}f=!1;if(b&64)if(g){if(b&128)throw new H(E.la);}else g=Jb(a,c,0),f=!0;if(!g)throw new H(E.A);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!J(g.mode))throw new H(E.U);if(!f&&(c=g?40960===(g.mode&61440)?E.$:J(g.mode)&&
("r"!==Bb(b)||b&512)?E.O:yb(g,Bb(b)):E.A))throw new H(c);b&512&&Rb(g,0);b&=-641;d=Gb({node:g,path:ub(g),flags:b,seekable:!0,position:0,f:g.f,Za:[],error:!1},d);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(Sb||(Sb={}),a in Sb||(Sb[a]=1,e.printErr("read file: "+a)));try{O.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),O.onOpenFile(a,g))}catch(k){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}
function Tb(a){a.fa&&(a.fa=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{M[a.fd]=null}}function Ub(a,b,c){if(!a.seekable||!a.f.D)throw new H(E.V);a.position=a.f.D(a,b,c);a.Za=[]}function Vb(a,b,c,d,f){if(0>d||0>f)throw new H(E.i);if(1===(a.flags&2097155))throw new H(E.G);if(J(a.node.mode))throw new H(E.O);if(!a.f.read)throw new H(E.i);var g=!0;if("undefined"===typeof f)f=a.position,g=!1;else if(!a.seekable)throw new H(E.V);b=a.f.read(a,b,c,d,f);g||(a.position+=b);return b}
function Wb(a,b,c,d,f,g){if(0>d||0>f)throw new H(E.i);if(0===(a.flags&2097155))throw new H(E.G);if(J(a.node.mode))throw new H(E.O);if(!a.f.write)throw new H(E.i);a.flags&1024&&Ub(a,0,2);var k=!0;if("undefined"===typeof f)f=a.position,k=!1;else if(!a.seekable)throw new H(E.V);b=a.f.write(a,b,c,d,f,g);k||(a.position+=b);try{if(a.path&&O.onWriteToFile)O.onWriteToFile(a.path)}catch(n){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+n.message)}return b}
function Xb(){H||(H=function(a,b){this.node=b;this.Ta=function(a){this.g=a;for(var b in E)if(E[b]===a){this.code=b;break}};this.Ta(a);this.message=Wa[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},H.prototype=Error(),H.prototype.constructor=H,[E.A].forEach(function(a){nb[a]=new H(a);nb[a].stack="<generic error, no stack>"}))}var Yb;function Zb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function $b(a,b,c){a=F("/dev",a);var d=Zb(!!b,!!c);ac||(ac=64);var f=ac++<<8|0;fb(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,k=0;k<f;k++){try{var n=b()}catch(na){throw new H(E.T);}if(void 0===n&&0===g)throw new H(E.ka);if(null===n||void 0===n)break;g++;c[d+k]=n}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(y){throw new H(E.T);}f&&(a.node.timestamp=Date.now());
return g}});Kb(a,d,f)}var ac,FS={},zb,Hb,Sb;
function bc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&Za(b)!==Za(ub(f.node)))return-E.U;throw f;}t[c>>2]=d.dev;t[c+4>>2]=0;t[c+8>>2]=d.ino;t[c+12>>2]=d.mode;t[c+16>>2]=d.nlink;t[c+20>>2]=d.uid;t[c+24>>2]=d.gid;t[c+28>>2]=d.rdev;t[c+32>>2]=0;t[c+36>>2]=d.size;t[c+40>>2]=4096;t[c+44>>2]=d.blocks;t[c+48>>2]=d.atime.getTime()/1E3|0;t[c+52>>2]=0;t[c+56>>2]=d.mtime.getTime()/1E3|0;t[c+60>>2]=0;t[c+64>>2]=d.ctime.getTime()/1E3|0;t[c+68>>2]=0;t[c+72>>2]=d.ino;return 0}var T=0;
function U(){T+=4;return t[T-4>>2]}function V(){return C(U())}function W(){var a=M[U()];if(!a)throw new H(E.G);return a}function dc(a,b){T=b;return 0}var ec=q;q+=16;var fc,X={};function hc(a){if(0===a)return 0;a=C(a);if(!X.hasOwnProperty(a))return 0;hc.ea&&ic(hc.ea);a=X[a];var b=Ca(a)+1,c=xa(b);c&&Ba(a,z,c,b);hc.ea=c;return hc.ea}var Y=q;q+=48;var jc=wa(ib("GMT"),2);
function kc(a){a/=1E3;if((l||m)&&self.performance&&self.performance.now)for(var b=self.performance.now();self.performance.now()-b<a;);else for(b=Date.now();Date.now()-b<a;);return 0}e._usleep=kc;function lc(a){return 0===a%4&&(0!==a%100||0===a%400)}function mc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var nc=[31,29,31,30,31,30,31,31,30,31,30,31],pc=[31,28,31,30,31,30,31,31,30,31,30,31];
function qc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(lc(a.getFullYear())?nc:pc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}Xb();N=Array(4096);Ib(I,"/");Q("/tmp");Q("/home");Q("/home/web_user");
(function(){Q("/dev");fb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Kb("/dev/null",259);eb(1280,jb);eb(1536,kb);Kb("/dev/tty",1280);Kb("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else b=p?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};$b("random",b);$b("urandom",b);Q("/dev/shm");Q("/dev/shm/tmp")})();Q("/proc");Q("/proc/self");Q("/proc/self/fd");
Ib({o:function(){var a=mb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=M[+c];if(!b)throw new H(E.G);a={parent:null,o:{ya:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Na.unshift(function(){if(!e.noFSInit&&!Yb){assert(!Yb,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Yb=!0;Xb();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?$b("stdin",e.stdin):Lb("/dev/tty","/dev/stdin");e.stdout?$b("stdout",null,e.stdout):Lb("/dev/tty","/dev/stdout");e.stderr?$b("stderr",null,e.stderr):Lb("/dev/tty1","/dev/stderr");var a=R("/dev/stdin",
"r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=R("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=R("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Oa.push(function(){sb=!1});Pa.push(function(){Yb=!1;var a=e._fflush;a&&a(0);for(a=0;a<M.length;a++){var b=M[a];b&&Tb(b)}});Na.unshift(function(){});Pa.push(function(){});if(p){var fs=require("fs"),ob=require("path");L.Ua()}var rc,Z;
fc?(Z=t[ec>>2],rc=t[Z>>2]):(fc=!0,X.USER=X.LOGNAME="web_user",X.PATH="/",X.PWD="/",X.HOME="/home/web_user",X.LANG="C.UTF-8",X._=e.thisProgram,rc=fa(1024),Z=fa(256),t[Z>>2]=rc,t[ec>>2]=Z);var sc=[],tc=0,uc;for(uc in X)if("string"===typeof X[uc]){var vc=uc+"="+X[uc];sc.push(vc);tc+=vc.length}if(1024<tc)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");
for(var wc=0;wc<sc.length;wc++){for(var xc=vc=sc[wc],yc=rc,zc=0;zc<xc.length;++zc)z[yc++>>0]=xc.charCodeAt(zc);z[yc>>0]=0;t[Z+4*wc>>2]=rc;rc+=vc.length+1}t[Z+4*sc.length>>2]=0;r=fa(4);Ga=Ha=ka(q);Ia=Ga+Ka;Ja=ka(Ia);t[r>>2]=Ja;ha=!0;function ib(a,b){var c=Array(Ca(a)+1);a=Ba(a,c,0,c.length);b&&(c.length=a);return c}e.wasmTableSize=4352;e.wasmMaxTableSize=4352;e.Ea={};
e.Fa={abort:x,enlargeMemory:function(){ja()},getTotalMemory:function(){return u},abortOnCannotGrowMemory:ja,jsCall_i:function(a){return w[a]()},jsCall_ii:function(a,b){return w[a](b)},jsCall_iii:function(a,b,c){return w[a](b,c)},jsCall_iiii:function(a,b,c,d){return w[a](b,c,d)},jsCall_iiiii:function(a,b,c,d,f){return w[a](b,c,d,f)},jsCall_iiiiii:function(a,b,c,d,f,g){return w[a](b,c,d,f,g)},jsCall_iiiiiii:function(a,b,c,d,f,g,k){return w[a](b,c,d,f,g,k)},jsCall_iiiij:function(a,b,c,d,f){return w[a](b,
c,d,f)},jsCall_iij:function(a,b,c){return w[a](b,c)},jsCall_iiji:function(a,b,c,d){return w[a](b,c,d)},jsCall_iijii:function(a,b,c,d,f){return w[a](b,c,d,f)},jsCall_vi:function(a,b){w[a](b)},jsCall_vii:function(a,b,c){w[a](b,c)},jsCall_viii:function(a,b,c,d){w[a](b,c,d)},jsCall_viiii:function(a,b,c,d,f){w[a](b,c,d,f)},jsCall_viiiij:function(a,b,c,d,f,g){w[a](b,c,d,f,g)},jsCall_viji:function(a,b,c,d){w[a](b,c,d)},___assert_fail:function(a,b,c,d){x("Assertion failed: "+C(a)+", at: "+[b?C(b):"unknown filename",
c,d?C(d):"unknown function"])},___setErrNo:Xa,___syscall10:function(a,b){T=b;try{var c=V();Mb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof H||x(d),-d.g}},___syscall118:function(a,b){T=b;try{return W(),0}catch(c){return"undefined"!==typeof FS&&c instanceof H||x(c),-c.g}},___syscall140:function(a,b){T=b;try{var c=W();U();var d=U(),f=U(),g=U();Ub(c,d,g);t[f>>2]=c.position;c.fa&&0===d&&0===g&&(c.fa=null);return 0}catch(k){return"undefined"!==typeof FS&&k instanceof H||x(k),-k.g}},
___syscall15:function(a,b){T=b;try{var c=V(),d=U();Pb(c,d);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof H||x(f),-f.g}},___syscall183:function(a,b){T=b;try{var c=U(),d=U();if(0===d)return-E.i;if(d<Ca("/")+1)return-E.Da;Ba("/",B,c,d);return c}catch(f){return"undefined"!==typeof FS&&f instanceof H||x(f),-f.g}},___syscall194:function(a,b){T=b;try{var c=U();assert(0===U());var d=U(),f=U();0<=d?assert(0===f):assert(-1===f);var g=M[c];if(!g)throw new H(E.G);if(0===(g.flags&2097155))throw new H(E.i);
Rb(g.node,d);return 0}catch(k){return"undefined"!==typeof FS&&k instanceof H||x(k),-k.g}},___syscall195:function(a,b){T=b;try{var c=V(),d=U();return bc(Nb,c,d)}catch(f){return"undefined"!==typeof FS&&f instanceof H||x(f),-f.g}},___syscall196:function(a,b){T=b;try{var c=V(),d=U();return bc(Ob,c,d)}catch(f){return"undefined"!==typeof FS&&f instanceof H||x(f),-f.g}},___syscall197:function(a,b){T=b;try{var c=W(),d=U();return bc(Nb,c.path,d)}catch(f){return"undefined"!==typeof FS&&f instanceof H||x(f),
-f.g}},___syscall20:function(a,b){T=b;return 42},___syscall201:function(){return dc.apply(null,arguments)},___syscall207:function(a,b){T=b;try{var c=U();U();U();var d=M[c];if(!d)throw new H(E.G);Qb(d.node);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof H||x(f),-f.g}},___syscall212:function(a,b){T=b;try{var c=V();U();U();Qb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof H||x(d),-d.g}},___syscall221:function(a,b){T=b;try{var c=W();switch(U()){case 0:var d=U();return 0>
d?-E.i:R(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=U(),c.flags|=d,0;case 12:case 12:return d=U(),pa[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-E.i;case 9:return Xa(E.i),-1;default:return-E.i}}catch(f){return"undefined"!==typeof FS&&f instanceof H||x(f),-f.g}},___syscall3:function(a,b){T=b;try{var c=W(),d=U(),f=U();return Vb(c,z,d,f)}catch(g){return"undefined"!==typeof FS&&g instanceof H||x(g),-g.g}},___syscall33:function(a,
b){T=b;try{var c=V();var d=U();if(d&-8)var f=-E.i;else{var g=P(c,{I:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");f=a&&yb(g,a)?-E.S:0}return f}catch(k){return"undefined"!==typeof FS&&k instanceof H||x(k),-k.g}},___syscall39:function(a,b){T=b;try{var c=V(),d=U();a=c;a=Za(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));Q(a,d);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof H||x(f),-f.g}},___syscall4:function(a,b){T=b;try{var c=W(),d=U(),f=U();return Wb(c,z,d,f)}catch(g){return"undefined"!==
typeof FS&&g instanceof H||x(g),-g.g}},___syscall40:function(a,b){T=b;try{var c=V(),d=P(c,{parent:!0}).node,f=ab(c),g=K(d,f),k=Eb(d,f,!0);if(k)throw new H(k);if(!d.c.rmdir)throw new H(E.B);if(g.K)throw new H(E.N);try{O.willDeletePath&&O.willDeletePath(c)}catch(n){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+n.message)}d.c.rmdir(d,f);xb(g);try{if(O.onDeletePath)O.onDeletePath(c)}catch(n){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+
n.message)}return 0}catch(n){return"undefined"!==typeof FS&&n instanceof H||x(n),-n.g}},___syscall5:function(a,b){T=b;try{var c=V(),d=U(),f=U();return R(c,d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof H||x(g),-g.g}},___syscall6:function(a,b){T=b;try{var c=W();Tb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof H||x(d),-d.g}},___syscall85:function(a,b){T=b;try{var c=V(),d=U();var f=U();if(0>=f)var g=-E.i;else{var k=tb(c),n=Math.min(f,Ca(k)),G=z[d+n];Ba(k,B,d,f+1);z[d+
n]=G;g=n}return g}catch(v){return"undefined"!==typeof FS&&v instanceof H||x(v),-v.g}},___syscall94:function(a,b){T=b;try{var c=U(),d=U(),f=M[c];if(!f)throw new H(E.G);Pb(f.node,d);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof H||x(g),-g.g}},_emscripten_memcpy_big:function(a,b,c){B.set(B.subarray(b,b+c),a);return a},_getenv:hc,_gettimeofday:function(a){var b=Date.now();t[a>>2]=b/1E3|0;t[a+4>>2]=b%1E3*1E3|0;return 0},_gmtime:function(a){a=new Date(1E3*t[a>>2]);t[Y>>2]=a.getUTCSeconds();
t[Y+4>>2]=a.getUTCMinutes();t[Y+8>>2]=a.getUTCHours();t[Y+12>>2]=a.getUTCDate();t[Y+16>>2]=a.getUTCMonth();t[Y+20>>2]=a.getUTCFullYear()-1900;t[Y+24>>2]=a.getUTCDay();t[Y+36>>2]=0;t[Y+32>>2]=0;t[Y+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;t[Y+40>>2]=jc;return Y},_nanosleep:function(a,b){var c=t[a>>2];a=t[a+4>>2];0!==b&&(t[b>>2]=0,t[b+4>>2]=0);return kc(1E6*c+a/1E3)},_sqlite3CodeSubselect:function(){e.printErr("missing function: sqlite3CodeSubselect");x(-1)},_sqlite3ExprForVectorField:function(){e.printErr("missing function: sqlite3ExprForVectorField");
x(-1)},_sqlite3VectorFieldSubexpr:function(){e.printErr("missing function: sqlite3VectorFieldSubexpr");x(-1)},_strftime:function(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function n(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-
1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function G(a){a=qc(new Date(a.m+1900,0,1),a.Z);var b=n(new Date(a.getFullYear()+1,0,4));return 0>=k(n(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var v=t[d+40>>2];d={Xa:t[d>>2],Wa:t[d+4>>2],Y:t[d+
8>>2],J:t[d+12>>2],F:t[d+16>>2],m:t[d+20>>2],Aa:t[d+24>>2],Z:t[d+28>>2],gd:t[d+32>>2],Va:t[d+36>>2],Ya:v?C(v):""};c=C(c);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var y in v)c=c.replace(new RegExp(y,"g"),v[y]);var ma="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),na="January February March April May June July August September October November December".split(" ");
v={"%a":function(a){return ma[a.Aa].substring(0,3)},"%A":function(a){return ma[a.Aa]},"%b":function(a){return na[a.F].substring(0,3)},"%B":function(a){return na[a.F]},"%C":function(a){return g((a.m+1900)/100|0,2)},"%d":function(a){return g(a.J,2)},"%e":function(a){return f(a.J,2," ")},"%g":function(a){return G(a).toString().substring(2)},"%G":function(a){return G(a)},"%H":function(a){return g(a.Y,2)},"%I":function(a){a=a.Y;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.J+mc(lc(a.m+
1900)?nc:pc,a.F-1),3)},"%m":function(a){return g(a.F+1,2)},"%M":function(a){return g(a.Wa,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.Y&&12>a.Y?"AM":"PM"},"%S":function(a){return g(a.Xa,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.m+1900,a.F+1,a.J,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.m+1900,0,1),c=0===b.getDay()?b:qc(b,7-b.getDay());a=new Date(a.m+1900,a.F,a.J);return 0>k(c,a)?g(Math.ceil((31-c.getDate()+(mc(lc(a.getFullYear())?nc:pc,a.getMonth()-
1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=n(new Date(a.m+1900,0,4)),c=n(new Date(a.m+1901,0,4)),d=qc(new Date(a.m+1900,0,1),a.Z);return 0>k(d,b)?"53":0>=k(c,d)?"01":g(Math.ceil((b.getFullYear()<a.m+1900?a.Z+32-b.getDate():a.Z+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.m+1900,a.F+1,a.J,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.m,0,1),c=1===b.getDay()?b:qc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.m+1900,a.F,a.J);return 0>k(c,a)?g(Math.ceil((31-
c.getDate()+(mc(lc(a.getFullYear())?nc:pc,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%y":function(a){return(a.m+1900).toString().substring(2)},"%Y":function(a){return a.m+1900},"%z":function(a){a=a.Va;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Ya},"%%":function(){return"%"}};for(y in v)0<=c.indexOf(y)&&(c=c.replace(new RegExp(y,"g"),v[y](d)));y=ib(c,!1);if(y.length>b)return 0;z.set(y,a);return y.length-1},_time:function(a){var b=
Date.now()/1E3|0;a&&(t[a>>2]=b);return b},_utimes:function(a,b){if(b){var c=1E3*t[b+8>>2];c+=t[b+12>>2]/1E3}else c=Date.now();a=C(a);try{b=c;var d=P(a,{I:!0}).node;d.c.l(d,{timestamp:Math.max(b,c)});return 0}catch(f){a=f;if(!(a instanceof H)){a+=" : ";a:{d=Error();if(!d.stack){try{throw Error(0);}catch(g){d=g}if(!d.stack){d="(no stack trace available)";break a}}d=d.stack.toString()}e.extraStackTrace&&(d+="\n"+e.extraStackTrace());d=Da(d);throw a+d;}Xa(a.g);return-1}},DYNAMICTOP_PTR:r,STACKTOP:Ha};
var Ac=e.asm(e.Ea,e.Fa,buffer);e.asm=Ac;e._RegisterExtensionFunctions=function(){return e.asm._RegisterExtensionFunctions.apply(null,arguments)};e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};var ic=e._free=function(){return e.asm._free.apply(null,arguments)},xa=e._malloc=function(){return e.asm._malloc.apply(null,arguments)};e._sqlite3_bind_blob=function(){return e.asm._sqlite3_bind_blob.apply(null,arguments)};
e._sqlite3_bind_double=function(){return e.asm._sqlite3_bind_double.apply(null,arguments)};e._sqlite3_bind_int=function(){return e.asm._sqlite3_bind_int.apply(null,arguments)};e._sqlite3_bind_parameter_index=function(){return e.asm._sqlite3_bind_parameter_index.apply(null,arguments)};e._sqlite3_bind_text=function(){return e.asm._sqlite3_bind_text.apply(null,arguments)};e._sqlite3_changes=function(){return e.asm._sqlite3_changes.apply(null,arguments)};
e._sqlite3_clear_bindings=function(){return e.asm._sqlite3_clear_bindings.apply(null,arguments)};e._sqlite3_close_v2=function(){return e.asm._sqlite3_close_v2.apply(null,arguments)};e._sqlite3_column_blob=function(){return e.asm._sqlite3_column_blob.apply(null,arguments)};e._sqlite3_column_bytes=function(){return e.asm._sqlite3_column_bytes.apply(null,arguments)};e._sqlite3_column_double=function(){return e.asm._sqlite3_column_double.apply(null,arguments)};
e._sqlite3_column_name=function(){return e.asm._sqlite3_column_name.apply(null,arguments)};e._sqlite3_column_text=function(){return e.asm._sqlite3_column_text.apply(null,arguments)};e._sqlite3_column_type=function(){return e.asm._sqlite3_column_type.apply(null,arguments)};e._sqlite3_create_function_v2=function(){return e.asm._sqlite3_create_function_v2.apply(null,arguments)};e._sqlite3_data_count=function(){return e.asm._sqlite3_data_count.apply(null,arguments)};
e._sqlite3_errmsg=function(){return e.asm._sqlite3_errmsg.apply(null,arguments)};e._sqlite3_exec=function(){return e.asm._sqlite3_exec.apply(null,arguments)};e._sqlite3_finalize=function(){return e.asm._sqlite3_finalize.apply(null,arguments)};e._sqlite3_free=function(){return e.asm._sqlite3_free.apply(null,arguments)};e._sqlite3_open=function(){return e.asm._sqlite3_open.apply(null,arguments)};e._sqlite3_prepare_v2=function(){return e.asm._sqlite3_prepare_v2.apply(null,arguments)};
e._sqlite3_reset=function(){return e.asm._sqlite3_reset.apply(null,arguments)};e._sqlite3_result_double=function(){return e.asm._sqlite3_result_double.apply(null,arguments)};e._sqlite3_result_null=function(){return e.asm._sqlite3_result_null.apply(null,arguments)};e._sqlite3_result_text=function(){return e.asm._sqlite3_result_text.apply(null,arguments)};e._sqlite3_step=function(){return e.asm._sqlite3_step.apply(null,arguments)};
e._sqlite3_value_blob=function(){return e.asm._sqlite3_value_blob.apply(null,arguments)};e._sqlite3_value_bytes=function(){return e.asm._sqlite3_value_bytes.apply(null,arguments)};e._sqlite3_value_double=function(){return e.asm._sqlite3_value_double.apply(null,arguments)};e._sqlite3_value_int=function(){return e.asm._sqlite3_value_int.apply(null,arguments)};e._sqlite3_value_text=function(){return e.asm._sqlite3_value_text.apply(null,arguments)};
e._sqlite3_value_type=function(){return e.asm._sqlite3_value_type.apply(null,arguments)};var ya=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.asm=Ac;function ea(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ea.prototype=Error();ea.prototype.constructor=ea;var Bc=null;Ua=function Cc(){e.calledRun||Dc();e.calledRun||(Ua=Cc)};
function Dc(){function a(){if(!e.calledRun&&(e.calledRun=!0,!la)){Ra||(Ra=!0,La(Na));La(Oa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Qa.unshift(a)}La(Qa)}}null===Bc&&(Bc=Date.now());if(!(0<D)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Sa();La(Ma);0<D||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=Dc;e.exit=function(a,b){if(!b||!e.noExitRuntime||0!==a){if(!e.noExitRuntime&&(la=!0,Ha=void 0,La(Pa),e.onExit))e.onExit(a);p&&process.exit(a);e.quit(a,new ea(a))}};function x(a){if(e.onAbort)e.onAbort(a);void 0!==a?(e.print(a),e.printErr(a),a=JSON.stringify(a)):a="";la=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=x;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;Dc();
var Fc=window.SQL||{};
e.onRuntimeInitialized=function(){var a=e.Runtime;var b=a.ja(4);var c=function(){function a(a,b){this.j=a;this.db=b;this.C=1;this.ba=[]}a.prototype.bind=function(a){if(!this.j)throw"Statement closed";this.reset();return Array.isArray(a)?this.Ha(a):this.Ia(a)};a.prototype.step=function(){var a;if(!this.j)throw"Statement closed";this.C=1;switch(a=oc(this.j)){case 100:return!0;case 101:return!1;default:return this.db.handleError(a)}};a.prototype.Oa=function(a){null==a&&(a=this.C++);return Gc(this.j,
a)};a.prototype.Pa=function(a){null==a&&(a=this.C++);return Hc(this.j,a)};a.prototype.getBlob=function(a){var b;null==a&&(a=this.C++);var c=Ic(this.j,a);var d=Jc(this.j,a);var f=new Uint8Array(c);for(a=b=0;0<=c?b<c:b>c;a=0<=c?++b:--b)f[a]=z[d+a];return f};a.prototype.get=function(a){var b,c;null!=a&&this.bind(a)&&this.step();var d=[];a=b=0;for(c=cc(this.j);0<=c?b<c:b>c;a=0<=c?++b:--b)switch(Kc(this.j,a)){case 1:case 2:d.push(this.Oa(a));break;case 3:d.push(this.Pa(a));break;case 4:d.push(this.getBlob(a));
break;default:d.push(null)}return d};a.prototype.getColumnNames=function(){var a,b;var c=[];var d=a=0;for(b=cc(this.j);0<=b?a<b:a>b;d=0<=b?++a:--a)c.push(Lc(this.j,d));return c};a.prototype.getAsObject=function(a){var b,c;var d=this.get(a);var f=this.getColumnNames();var g={};a=b=0;for(c=f.length;b<c;a=++b){var S=f[a];g[S]=d[a]}return g};a.prototype.run=function(a){null!=a&&this.bind(a);this.step();return this.reset()};a.prototype.La=function(a,b){var c;null==b&&(b=this.C++);a=ib(a);this.ba.push(c=
wa(a,0));this.db.handleError(y(this.j,b,c,a.length-1,0))};a.prototype.Ga=function(a,b){var c;null==b&&(b=this.C++);this.ba.push(c=wa(a,0));this.db.handleError(ma(this.j,b,c,a.length,0))};a.prototype.Ka=function(a,b){null==b&&(b=this.C++);this.db.handleError((a===(a|0)?Cb:na)(this.j,b,a))};a.prototype.Ja=function(a){null==a&&(a=this.C++);ma(this.j,a,0,0,0)};a.prototype.pa=function(a,b){null==b&&(b=this.C++);switch(typeof a){case "string":this.La(a,b);break;case "number":case "boolean":this.Ka(a+0,
b);break;case "object":if(null===a)this.Ja(b);else if(null!=a.length)this.Ga(a,b);else throw"Wrong API use : tried to bind a value of an unknown type ("+a+").";}};a.prototype.Ia=function(a){var b;for(b in a){var c=a[b];var d=gb(this.j,b);0!==d&&this.pa(c,d)}return!0};a.prototype.Ha=function(a){var b,c;var d=b=0;for(c=a.length;b<c;d=++b){var f=a[d];this.pa(f,d+1)}return!0};a.prototype.reset=function(){this.freemem();return 0===Mc(this.j)&&0===Nc(this.j)};a.prototype.freemem=function(){for(var a;a=
this.ba.pop();)ic(a);return null};a.prototype.free=function(){this.freemem();var a=0===Oc(this.j);delete this.db.X[this.j];this.j=0;return a};return a}();var d=function(){function d(a){this.filename="dbfile_"+(4294967295*Math.random()>>>0);if(null!=a){var c=this.filename,d=c?F("/",c):"/";c=Zb(!0,!0);d=Jb(d,(void 0!==c?c:438)&4095|32768,0);if(a){if("string"===typeof a){for(var g=Array(a.length),k=0,S=a.length;k<S;++k)g[k]=a.charCodeAt(k);a=g}Pb(d,c|146);g=R(d,"w");Wb(g,a,0,a.length,0,void 0);Tb(g);
Pb(d,c)}}this.handleError(f(this.filename,b));this.db=A(b,"i32");Pc(this.db);this.X={}}d.prototype.run=function(a,c){if(!this.db)throw"Database closed";c?(a=this.prepare(a,c),a.step(),a.free()):this.handleError(k(this.db,a,0,0,b));return this};d.prototype.exec=function(d){if(!this.db)throw"Database closed";var f=a.ed();a.ja(d.length<<3);var g=d.length<<3;var k=a.ja(g);Ba(d,B,k,g);d=a.ja(4);for(g=[];0!==A(k,"i8");){oa(b);oa(d);this.handleError(v(this.db,k,-1,b,d));var n=A(b,"i32");k=A(d,"i32");if(0!==
n){var S=new c(n,this);for(n=null;S.step();)null===n&&(n={columns:S.getColumnNames(),values:[]},g.push(n)),n.values.push(S.get());S.free()}}a.dd(f);return g};d.prototype.each=function(a,b,c,d){"function"===typeof b&&(d=c,c=b,b=void 0);for(a=this.prepare(a,b);a.step();)c(a.getAsObject());a.free();if("function"===typeof d)return d()};d.prototype.prepare=function(a,d){oa(b);this.handleError(G(this.db,a,-1,b,0));a=A(b,"i32");if(0===a)throw"Nothing to prepare";var f=new c(a,this);null!=d&&f.bind(d);return this.X[a]=
f};d.prototype["export"]=function(){var a;var c=this.X;for(k in c){var d=c[k];d.free()}this.handleError(g(this.db));d=this.filename;var k=k={encoding:"binary"};k.flags=k.flags||"r";k.encoding=k.encoding||"binary";if("utf8"!==k.encoding&&"binary"!==k.encoding)throw Error('Invalid encoding type "'+k.encoding+'"');c=R(d,k.flags);d=Nb(d).size;var n=new Uint8Array(d);Vb(c,n,0,d,0);"utf8"===k.encoding?a=za(n,0):"binary"===k.encoding&&(a=n);Tb(c);this.handleError(f(this.filename,b));this.db=A(b,"i32");return a};
d.prototype.close=function(){var a;var b=this.X;for(a in b){var c=b[a];c.free()}this.handleError(g(this.db));Mb("/"+this.filename);return this.db=null};d.prototype.handleError=function(a){if(0===a)return null;a=Ec(this.db);throw Error(a);};d.prototype.getRowsModified=function(){return n(this.db)};d.prototype.create_function=function(b,c){var d=a.Zc(function(a,b,d){var f,g;var k=[];for(f=g=0;0<=b?g<=b:g>=b;f=0<=b?++g:--g){var n=A(d+4*f,"i32");var v=Qc(n);f=function(){switch(!1){case 1!==v:return Rc;
case 2!==v:return Sc;case 3!==v:return Tc;case 4!==v:return function(a){var b,c;var d=Uc(a);var f=Vc(a);a=new Uint8Array(d);for(b=c=0;0<=d?c<d:c>d;b=0<=d?++c:--c)a[b]=z[f+b];return a};default:return function(){return null}}}();f=f(n);k.push(f)}if(b=c.apply(null,k))switch(typeof b){case "number":return Wc(a,b);case "string":return Xc(a,b,-1,-1)}else return Yc(a)});this.handleError(Zc(this.db,b,c.length,1,0,d,0,0,0));return this};return d}();var f=e.cwrap("sqlite3_open","number",["string","number"]);
var g=e.cwrap("sqlite3_close_v2","number",["number"]);var k=e.cwrap("sqlite3_exec","number",["number","string","number","number","number"]);e.cwrap("sqlite3_free","",["number"]);var n=e.cwrap("sqlite3_changes","number",["number"]);var G=e.cwrap("sqlite3_prepare_v2","number",["number","string","number","number","number"]);var v=e.cwrap("sqlite3_prepare_v2","number",["number","number","number","number","number"]);var y=e.cwrap("sqlite3_bind_text","number",["number","number","number","number","number"]);
var ma=e.cwrap("sqlite3_bind_blob","number",["number","number","number","number","number"]);var na=e.cwrap("sqlite3_bind_double","number",["number","number","number"]);var Cb=e.cwrap("sqlite3_bind_int","number",["number","number","number"]);var gb=e.cwrap("sqlite3_bind_parameter_index","number",["number","string"]);var oc=e.cwrap("sqlite3_step","number",["number"]);var Ec=e.cwrap("sqlite3_errmsg","string",["number"]);var cc=e.cwrap("sqlite3_data_count","number",["number"]);var Gc=e.cwrap("sqlite3_column_double",
"number",["number","number"]);var Hc=e.cwrap("sqlite3_column_text","string",["number","number"]);var Jc=e.cwrap("sqlite3_column_blob","number",["number","number"]);var Ic=e.cwrap("sqlite3_column_bytes","number",["number","number"]);var Kc=e.cwrap("sqlite3_column_type","number",["number","number"]);var Lc=e.cwrap("sqlite3_column_name","string",["number","number"]);var Nc=e.cwrap("sqlite3_reset","number",["number"]);var Mc=e.cwrap("sqlite3_clear_bindings","number",["number"]);var Oc=e.cwrap("sqlite3_finalize",
"number",["number"]);var Zc=e.cwrap("sqlite3_create_function_v2","number","number string number number number number number number number".split(" "));var Qc=e.cwrap("sqlite3_value_type","number",["number"]);var Uc=e.cwrap("sqlite3_value_bytes","number",["number"]);var Tc=e.cwrap("sqlite3_value_text","string",["number"]);var Rc=e.cwrap("sqlite3_value_int","number",["number"]);var Vc=e.cwrap("sqlite3_value_blob","number",["number"]);var Sc=e.cwrap("sqlite3_value_double","number",["number"]);var Wc=
e.cwrap("sqlite3_result_double","",["number","number"]);var Yc=e.cwrap("sqlite3_result_null","",["number"]);var Xc=e.cwrap("sqlite3_result_text","",["number","string","number","number"]);var Pc=e.cwrap("RegisterExtensionFunctions","number",["number"]);this.SQL={Database:d};e.Yc=Fc;if("function"===typeof Fc.onRuntimeInitialized)Fc.onRuntimeInitialized()}.bind(this);if("undefined"!==typeof module)e.onRuntimeInitialized();
return this['SQL'];
})();
if (typeof module !== 'undefined') module.exports = SQL;
if (typeof define === 'function') define(SQL);
